// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module corr_accel_compute (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reg_file_0_0_address0,
        reg_file_0_0_ce0,
        reg_file_0_0_q0,
        reg_file_2_0_address0,
        reg_file_2_0_ce0,
        reg_file_2_0_we0,
        reg_file_2_0_d0,
        reg_file_2_0_q0,
        reg_file_2_0_address1,
        reg_file_2_0_ce1,
        reg_file_2_0_q1,
        reg_file_2_1_address0,
        reg_file_2_1_ce0,
        reg_file_2_1_we0,
        reg_file_2_1_d0,
        reg_file_2_1_q0,
        reg_file_2_1_address1,
        reg_file_2_1_ce1,
        reg_file_2_1_q1,
        reg_file_4_0_address0,
        reg_file_4_0_ce0,
        reg_file_4_0_we0,
        reg_file_4_0_d0,
        reg_file_4_0_q0,
        reg_file_4_0_address1,
        reg_file_4_0_ce1,
        reg_file_4_0_we1,
        reg_file_4_0_d1,
        reg_file_4_0_q1,
        reg_file_4_1_address0,
        reg_file_4_1_ce0,
        reg_file_4_1_we0,
        reg_file_4_1_d0,
        reg_file_4_1_q0,
        reg_file_4_1_address1,
        reg_file_4_1_ce1,
        reg_file_4_1_we1,
        reg_file_4_1_d1,
        reg_file_4_1_q1,
        reg_file_5_0_address0,
        reg_file_5_0_ce0,
        reg_file_5_0_we0,
        reg_file_5_0_d0,
        reg_file_5_0_address1,
        reg_file_5_0_ce1,
        reg_file_5_0_q1,
        reg_file_5_1_address0,
        reg_file_5_1_ce0,
        reg_file_5_1_we0,
        reg_file_5_1_d0,
        reg_file_5_1_address1,
        reg_file_5_1_ce1,
        reg_file_5_1_q1,
        reg_file_6_0_address0,
        reg_file_6_0_ce0,
        reg_file_6_0_we0,
        reg_file_6_0_d0,
        reg_file_6_0_q0,
        reg_file_6_0_address1,
        reg_file_6_0_ce1,
        reg_file_6_0_we1,
        reg_file_6_0_d1,
        reg_file_6_1_address0,
        reg_file_6_1_ce0,
        reg_file_6_1_we0,
        reg_file_6_1_d0,
        reg_file_6_1_q0,
        reg_file_6_1_address1,
        reg_file_6_1_ce1,
        reg_file_6_1_we1,
        reg_file_6_1_d1
);

parameter    ap_ST_fsm_state1 = 16'd1;
parameter    ap_ST_fsm_state2 = 16'd2;
parameter    ap_ST_fsm_state3 = 16'd4;
parameter    ap_ST_fsm_state4 = 16'd8;
parameter    ap_ST_fsm_state5 = 16'd16;
parameter    ap_ST_fsm_state6 = 16'd32;
parameter    ap_ST_fsm_state7 = 16'd64;
parameter    ap_ST_fsm_state8 = 16'd128;
parameter    ap_ST_fsm_state9 = 16'd256;
parameter    ap_ST_fsm_state10 = 16'd512;
parameter    ap_ST_fsm_state11 = 16'd1024;
parameter    ap_ST_fsm_state12 = 16'd2048;
parameter    ap_ST_fsm_state13 = 16'd4096;
parameter    ap_ST_fsm_state14 = 16'd8192;
parameter    ap_ST_fsm_state15 = 16'd16384;
parameter    ap_ST_fsm_state16 = 16'd32768;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] reg_file_0_0_address0;
output   reg_file_0_0_ce0;
input  [15:0] reg_file_0_0_q0;
output  [10:0] reg_file_2_0_address0;
output   reg_file_2_0_ce0;
output   reg_file_2_0_we0;
output  [15:0] reg_file_2_0_d0;
input  [15:0] reg_file_2_0_q0;
output  [10:0] reg_file_2_0_address1;
output   reg_file_2_0_ce1;
input  [15:0] reg_file_2_0_q1;
output  [10:0] reg_file_2_1_address0;
output   reg_file_2_1_ce0;
output   reg_file_2_1_we0;
output  [15:0] reg_file_2_1_d0;
input  [15:0] reg_file_2_1_q0;
output  [10:0] reg_file_2_1_address1;
output   reg_file_2_1_ce1;
input  [15:0] reg_file_2_1_q1;
output  [10:0] reg_file_4_0_address0;
output   reg_file_4_0_ce0;
output   reg_file_4_0_we0;
output  [15:0] reg_file_4_0_d0;
input  [15:0] reg_file_4_0_q0;
output  [10:0] reg_file_4_0_address1;
output   reg_file_4_0_ce1;
output   reg_file_4_0_we1;
output  [15:0] reg_file_4_0_d1;
input  [15:0] reg_file_4_0_q1;
output  [10:0] reg_file_4_1_address0;
output   reg_file_4_1_ce0;
output   reg_file_4_1_we0;
output  [15:0] reg_file_4_1_d0;
input  [15:0] reg_file_4_1_q0;
output  [10:0] reg_file_4_1_address1;
output   reg_file_4_1_ce1;
output   reg_file_4_1_we1;
output  [15:0] reg_file_4_1_d1;
input  [15:0] reg_file_4_1_q1;
output  [10:0] reg_file_5_0_address0;
output   reg_file_5_0_ce0;
output   reg_file_5_0_we0;
output  [15:0] reg_file_5_0_d0;
output  [10:0] reg_file_5_0_address1;
output   reg_file_5_0_ce1;
input  [15:0] reg_file_5_0_q1;
output  [10:0] reg_file_5_1_address0;
output   reg_file_5_1_ce0;
output   reg_file_5_1_we0;
output  [15:0] reg_file_5_1_d0;
output  [10:0] reg_file_5_1_address1;
output   reg_file_5_1_ce1;
input  [15:0] reg_file_5_1_q1;
output  [10:0] reg_file_6_0_address0;
output   reg_file_6_0_ce0;
output   reg_file_6_0_we0;
output  [15:0] reg_file_6_0_d0;
input  [15:0] reg_file_6_0_q0;
output  [10:0] reg_file_6_0_address1;
output   reg_file_6_0_ce1;
output   reg_file_6_0_we1;
output  [15:0] reg_file_6_0_d1;
output  [10:0] reg_file_6_1_address0;
output   reg_file_6_1_ce0;
output   reg_file_6_1_we0;
output  [15:0] reg_file_6_1_d0;
input  [15:0] reg_file_6_1_q0;
output  [10:0] reg_file_6_1_address1;
output   reg_file_6_1_ce1;
output   reg_file_6_1_we1;
output  [15:0] reg_file_6_1_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg reg_file_0_0_ce0;
reg[10:0] reg_file_2_0_address0;
reg reg_file_2_0_ce0;
reg reg_file_2_0_we0;
reg[10:0] reg_file_2_0_address1;
reg reg_file_2_0_ce1;
reg[10:0] reg_file_2_1_address0;
reg reg_file_2_1_ce0;
reg reg_file_2_1_we0;
reg[10:0] reg_file_2_1_address1;
reg reg_file_2_1_ce1;
reg[10:0] reg_file_4_0_address0;
reg reg_file_4_0_ce0;
reg reg_file_4_0_we0;
reg[15:0] reg_file_4_0_d0;
reg[10:0] reg_file_4_0_address1;
reg reg_file_4_0_ce1;
reg reg_file_4_0_we1;
reg[10:0] reg_file_4_1_address0;
reg reg_file_4_1_ce0;
reg reg_file_4_1_we0;
reg[15:0] reg_file_4_1_d0;
reg[10:0] reg_file_4_1_address1;
reg reg_file_4_1_ce1;
reg reg_file_4_1_we1;
reg[10:0] reg_file_5_0_address0;
reg reg_file_5_0_ce0;
reg reg_file_5_0_we0;
reg[15:0] reg_file_5_0_d0;
reg[10:0] reg_file_5_0_address1;
reg reg_file_5_0_ce1;
reg[10:0] reg_file_5_1_address0;
reg reg_file_5_1_ce0;
reg reg_file_5_1_we0;
reg[15:0] reg_file_5_1_d0;
reg[10:0] reg_file_5_1_address1;
reg reg_file_5_1_ce1;
reg[10:0] reg_file_6_0_address0;
reg reg_file_6_0_ce0;
reg reg_file_6_0_we0;
reg reg_file_6_0_ce1;
reg reg_file_6_0_we1;
reg[10:0] reg_file_6_1_address0;
reg reg_file_6_1_ce0;
reg reg_file_6_1_we0;
reg reg_file_6_1_ce1;
reg reg_file_6_1_we1;

(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    ap_CS_fsm_state4;
reg   [15:0] reg_file_0_0_load_reg_156;
wire    ap_CS_fsm_state5;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_ce1;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_we1;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_d1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_ce1;
wire    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_we1;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_d1;
wire    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_d0;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_ce1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_ce1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_1_ce0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_0_ce0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_ce;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_ce;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_ce1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_ce1;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_ce;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_ce;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_1_ce0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_0_ce0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_ce1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_ce1;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_ce;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_ce;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_ce1;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_we1;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_d1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_ce1;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_we1;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_d1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_ce0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_ce1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_ce0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_ce1;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_1_ce0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_0_ce0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_ce1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_ce1;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_ce;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_ce;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_ce1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_ce1;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_ce;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_din0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_din1;
wire    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_ce;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_done;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_idle;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_ready;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_ce1;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_address0;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_ce0;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_we0;
wire   [15:0] grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_d0;
wire   [10:0] grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_address1;
wire    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_ce1;
reg    grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start_reg;
reg    grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start_reg;
wire    ap_CS_fsm_state6;
reg    grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start_reg;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
reg    grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start_reg;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
reg    grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start_reg;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
reg    grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg    grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start_reg;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire   [15:0] grp_fu_162_p2;
reg   [15:0] grp_fu_162_p0;
reg   [15:0] grp_fu_162_p1;
reg    grp_fu_162_ce;
wire   [15:0] grp_fu_166_p2;
reg   [15:0] grp_fu_166_p0;
reg   [15:0] grp_fu_166_p1;
reg    grp_fu_166_ce;
wire   [15:0] grp_fu_170_p2;
reg   [15:0] grp_fu_170_p0;
reg   [15:0] grp_fu_170_p1;
reg    grp_fu_170_ce;
wire   [15:0] grp_fu_174_p2;
reg   [15:0] grp_fu_174_p0;
reg   [15:0] grp_fu_174_p1;
reg    grp_fu_174_ce;
reg   [15:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
reg    ap_ST_fsm_state16_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 16'd1;
#0 grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start_reg = 1'b0;
#0 grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start_reg = 1'b0;
#0 grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start_reg = 1'b0;
#0 grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start_reg = 1'b0;
#0 grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start_reg = 1'b0;
#0 grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start_reg = 1'b0;
#0 grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start_reg = 1'b0;
#0 grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start_reg = 1'b0;
#0 grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start_reg = 1'b0;
end

corr_accel_compute_Pipeline_VITIS_LOOP_134_1 grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_ready),
    .reg_file_4_1_address0(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_address0),
    .reg_file_4_1_ce0(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_ce0),
    .reg_file_4_1_we0(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_we0),
    .reg_file_4_1_d0(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_d0),
    .reg_file_4_1_address1(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_address1),
    .reg_file_4_1_ce1(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_ce1),
    .reg_file_4_1_we1(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_we1),
    .reg_file_4_1_d1(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_d1),
    .reg_file_4_0_address0(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_address0),
    .reg_file_4_0_ce0(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_ce0),
    .reg_file_4_0_we0(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_we0),
    .reg_file_4_0_d0(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_d0),
    .reg_file_4_0_address1(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_address1),
    .reg_file_4_0_ce1(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_ce1),
    .reg_file_4_0_we1(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_we1),
    .reg_file_4_0_d1(grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_d1)
);

corr_accel_compute_Pipeline_VITIS_LOOP_156_5 grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_ready),
    .reg_file_5_1_address0(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_address0),
    .reg_file_5_1_ce0(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_ce0),
    .reg_file_5_1_we0(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_we0),
    .reg_file_5_1_d0(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_d0),
    .reg_file_5_0_address0(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_address0),
    .reg_file_5_0_ce0(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_ce0),
    .reg_file_5_0_we0(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_we0),
    .reg_file_5_0_d0(grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_d0)
);

corr_accel_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3 grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_ready),
    .reg_file_4_1_address0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_address0),
    .reg_file_4_1_ce0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_ce0),
    .reg_file_4_1_we0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_we0),
    .reg_file_4_1_d0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_d0),
    .reg_file_4_1_address1(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_address1),
    .reg_file_4_1_ce1(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_ce1),
    .reg_file_4_1_q1(reg_file_4_1_q1),
    .reg_file_4_0_address0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_address0),
    .reg_file_4_0_ce0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_ce0),
    .reg_file_4_0_we0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_we0),
    .reg_file_4_0_d0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_d0),
    .reg_file_4_0_address1(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_address1),
    .reg_file_4_0_ce1(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_ce1),
    .reg_file_4_0_q1(reg_file_4_0_q1),
    .reg_file_2_1_address0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_1_address0),
    .reg_file_2_1_ce0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_1_ce0),
    .reg_file_2_1_q0(reg_file_2_1_q0),
    .reg_file_2_0_address0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_0_address0),
    .reg_file_2_0_ce0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_0_ce0),
    .reg_file_2_0_q0(reg_file_2_0_q0),
    .grp_fu_162_p_din0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_din0),
    .grp_fu_162_p_din1(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_din1),
    .grp_fu_162_p_dout0(grp_fu_162_p2),
    .grp_fu_162_p_ce(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_ce),
    .grp_fu_166_p_din0(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_din0),
    .grp_fu_166_p_din1(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_din1),
    .grp_fu_166_p_dout0(grp_fu_166_p2),
    .grp_fu_166_p_ce(grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_ce)
);

corr_accel_compute_Pipeline_VITIS_LOOP_150_4 grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_ready),
    .reg_file_4_1_address0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_address0),
    .reg_file_4_1_ce0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_ce0),
    .reg_file_4_1_we0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_we0),
    .reg_file_4_1_d0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_d0),
    .reg_file_4_1_address1(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_address1),
    .reg_file_4_1_ce1(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_ce1),
    .reg_file_4_1_q1(reg_file_4_1_q1),
    .reg_file_4_0_address0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_address0),
    .reg_file_4_0_ce0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_ce0),
    .reg_file_4_0_we0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_we0),
    .reg_file_4_0_d0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_d0),
    .reg_file_4_0_address1(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_address1),
    .reg_file_4_0_ce1(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_ce1),
    .reg_file_4_0_q1(reg_file_4_0_q1),
    .val2_4(reg_file_0_0_load_reg_156),
    .grp_fu_170_p_din0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_din0),
    .grp_fu_170_p_din1(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_din1),
    .grp_fu_170_p_dout0(grp_fu_170_p2),
    .grp_fu_170_p_ce(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_ce),
    .grp_fu_174_p_din0(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_din0),
    .grp_fu_174_p_din1(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_din1),
    .grp_fu_174_p_dout0(grp_fu_174_p2),
    .grp_fu_174_p_ce(grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_ce)
);

corr_accel_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7 grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_ready),
    .reg_file_4_1_address0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_1_address0),
    .reg_file_4_1_ce0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_1_ce0),
    .reg_file_4_1_q0(reg_file_4_1_q0),
    .reg_file_4_0_address0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_0_address0),
    .reg_file_4_0_ce0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_0_ce0),
    .reg_file_4_0_q0(reg_file_4_0_q0),
    .reg_file_2_1_address0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_address0),
    .reg_file_2_1_ce0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_ce0),
    .reg_file_2_1_we0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_we0),
    .reg_file_2_1_d0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_d0),
    .reg_file_2_1_address1(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_address1),
    .reg_file_2_1_ce1(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_ce1),
    .reg_file_2_1_q1(reg_file_2_1_q1),
    .reg_file_2_0_address0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_address0),
    .reg_file_2_0_ce0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_ce0),
    .reg_file_2_0_we0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_we0),
    .reg_file_2_0_d0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_d0),
    .reg_file_2_0_address1(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_address1),
    .reg_file_2_0_ce1(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_ce1),
    .reg_file_2_0_q1(reg_file_2_0_q1),
    .grp_fu_162_p_din0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_din0),
    .grp_fu_162_p_din1(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_din1),
    .grp_fu_162_p_dout0(grp_fu_162_p2),
    .grp_fu_162_p_ce(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_ce),
    .grp_fu_166_p_din0(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_din0),
    .grp_fu_166_p_din1(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_din1),
    .grp_fu_166_p_dout0(grp_fu_166_p2),
    .grp_fu_166_p_ce(grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_ce)
);

corr_accel_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9 grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_ready),
    .reg_file_6_1_address0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_address0),
    .reg_file_6_1_ce0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_ce0),
    .reg_file_6_1_we0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_we0),
    .reg_file_6_1_d0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_d0),
    .reg_file_6_1_address1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_address1),
    .reg_file_6_1_ce1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_ce1),
    .reg_file_6_1_we1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_we1),
    .reg_file_6_1_d1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_d1),
    .reg_file_6_0_address0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_address0),
    .reg_file_6_0_ce0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_ce0),
    .reg_file_6_0_we0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_we0),
    .reg_file_6_0_d0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_d0),
    .reg_file_6_0_address1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_address1),
    .reg_file_6_0_ce1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_ce1),
    .reg_file_6_0_we1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_we1),
    .reg_file_6_0_d1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_d1),
    .reg_file_2_1_address0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_address0),
    .reg_file_2_1_ce0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_ce0),
    .reg_file_2_1_q0(reg_file_2_1_q0),
    .reg_file_2_1_address1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_address1),
    .reg_file_2_1_ce1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_ce1),
    .reg_file_2_1_q1(reg_file_2_1_q1),
    .reg_file_2_0_address0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_address0),
    .reg_file_2_0_ce0(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_ce0),
    .reg_file_2_0_q0(reg_file_2_0_q0),
    .reg_file_2_0_address1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_address1),
    .reg_file_2_0_ce1(grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_ce1),
    .reg_file_2_0_q1(reg_file_2_0_q1)
);

corr_accel_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11 grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_ready),
    .reg_file_6_1_address0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_1_address0),
    .reg_file_6_1_ce0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_1_ce0),
    .reg_file_6_1_q0(reg_file_6_1_q0),
    .reg_file_6_0_address0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_0_address0),
    .reg_file_6_0_ce0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_0_ce0),
    .reg_file_6_0_q0(reg_file_6_0_q0),
    .reg_file_5_1_address0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_address0),
    .reg_file_5_1_ce0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_ce0),
    .reg_file_5_1_we0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_we0),
    .reg_file_5_1_d0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_d0),
    .reg_file_5_1_address1(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_address1),
    .reg_file_5_1_ce1(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_ce1),
    .reg_file_5_1_q1(reg_file_5_1_q1),
    .reg_file_5_0_address0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_address0),
    .reg_file_5_0_ce0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_ce0),
    .reg_file_5_0_we0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_we0),
    .reg_file_5_0_d0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_d0),
    .reg_file_5_0_address1(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_address1),
    .reg_file_5_0_ce1(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_ce1),
    .reg_file_5_0_q1(reg_file_5_0_q1),
    .grp_fu_162_p_din0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_din0),
    .grp_fu_162_p_din1(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_din1),
    .grp_fu_162_p_dout0(grp_fu_162_p2),
    .grp_fu_162_p_ce(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_ce),
    .grp_fu_166_p_din0(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_din0),
    .grp_fu_166_p_din1(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_din1),
    .grp_fu_166_p_dout0(grp_fu_166_p2),
    .grp_fu_166_p_ce(grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_ce)
);

corr_accel_compute_Pipeline_VITIS_LOOP_190_12 grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_ready),
    .reg_file_5_1_address0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_address0),
    .reg_file_5_1_ce0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_ce0),
    .reg_file_5_1_we0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_we0),
    .reg_file_5_1_d0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_d0),
    .reg_file_5_1_address1(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_address1),
    .reg_file_5_1_ce1(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_ce1),
    .reg_file_5_1_q1(reg_file_5_1_q1),
    .reg_file_5_0_address0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_address0),
    .reg_file_5_0_ce0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_ce0),
    .reg_file_5_0_we0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_we0),
    .reg_file_5_0_d0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_d0),
    .reg_file_5_0_address1(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_address1),
    .reg_file_5_0_ce1(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_ce1),
    .reg_file_5_0_q1(reg_file_5_0_q1),
    .val2_4(reg_file_0_0_load_reg_156),
    .grp_fu_170_p_din0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_din0),
    .grp_fu_170_p_din1(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_din1),
    .grp_fu_170_p_dout0(grp_fu_170_p2),
    .grp_fu_170_p_ce(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_ce),
    .grp_fu_174_p_din0(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_din0),
    .grp_fu_174_p_din1(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_din1),
    .grp_fu_174_p_dout0(grp_fu_174_p2),
    .grp_fu_174_p_ce(grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_ce)
);

corr_accel_compute_Pipeline_VITIS_LOOP_199_13 grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start),
    .ap_done(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_done),
    .ap_idle(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_idle),
    .ap_ready(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_ready),
    .reg_file_5_1_address0(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_address0),
    .reg_file_5_1_ce0(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_ce0),
    .reg_file_5_1_we0(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_we0),
    .reg_file_5_1_d0(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_d0),
    .reg_file_5_1_address1(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_address1),
    .reg_file_5_1_ce1(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_ce1),
    .reg_file_5_1_q1(reg_file_5_1_q1),
    .reg_file_5_0_address0(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_address0),
    .reg_file_5_0_ce0(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_ce0),
    .reg_file_5_0_we0(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_we0),
    .reg_file_5_0_d0(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_d0),
    .reg_file_5_0_address1(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_address1),
    .reg_file_5_0_ce1(grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_ce1),
    .reg_file_5_0_q1(reg_file_5_0_q1)
);

corr_accel_hadd_16ns_16ns_16_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_2_full_dsp_1_U81(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_162_p0),
    .din1(grp_fu_162_p1),
    .ce(grp_fu_162_ce),
    .dout(grp_fu_162_p2)
);

corr_accel_hadd_16ns_16ns_16_2_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hadd_16ns_16ns_16_2_full_dsp_1_U82(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_166_p0),
    .din1(grp_fu_166_p1),
    .ce(grp_fu_166_ce),
    .dout(grp_fu_166_p2)
);

corr_accel_hdiv_16ns_16ns_16_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hdiv_16ns_16ns_16_5_no_dsp_1_U83(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_170_p0),
    .din1(grp_fu_170_p1),
    .ce(grp_fu_170_ce),
    .dout(grp_fu_170_p2)
);

corr_accel_hdiv_16ns_16ns_16_5_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
hdiv_16ns_16ns_16_5_no_dsp_1_U84(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_174_p0),
    .din1(grp_fu_174_p1),
    .ce(grp_fu_174_ce),
    .dout(grp_fu_174_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state7)) begin
            grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state9)) begin
            grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state11)) begin
            grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state15)) begin
            grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start_reg <= 1'b1;
        end else if ((grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_ready == 1'b1)) begin
            grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        reg_file_0_0_load_reg_156 <= reg_file_0_0_q0;
    end
end

always @ (*) begin
    if ((grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_done == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

assign ap_ST_fsm_state11_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_done == 1'b0)) begin
        ap_ST_fsm_state16_blk = 1'b1;
    end else begin
        ap_ST_fsm_state16_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_162_ce = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_162_ce = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_162_ce = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_ce;
    end else begin
        grp_fu_162_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_162_p0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_162_p0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_162_p0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_din0;
    end else begin
        grp_fu_162_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_162_p1 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_162_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_162_p1 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_162_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_162_p1 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_162_p_din1;
    end else begin
        grp_fu_162_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_166_ce = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_166_ce = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_166_ce = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_ce;
    end else begin
        grp_fu_166_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_166_p0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_166_p0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_166_p0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_din0;
    end else begin
        grp_fu_166_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_166_p1 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_grp_fu_166_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_166_p1 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_grp_fu_166_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_166_p1 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_grp_fu_166_p_din1;
    end else begin
        grp_fu_166_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_170_ce = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_170_ce = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_ce;
    end else begin
        grp_fu_170_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_170_p0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_170_p0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_din0;
    end else begin
        grp_fu_170_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_170_p1 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_170_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_170_p1 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_170_p_din1;
    end else begin
        grp_fu_170_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_174_ce = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_174_ce = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_ce;
    end else begin
        grp_fu_174_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_174_p0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_174_p0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_din0;
    end else begin
        grp_fu_174_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_174_p1 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_grp_fu_174_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_174_p1 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_grp_fu_174_p_din1;
    end else begin
        grp_fu_174_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_done == 1'b1))) begin
        reg_file_0_0_ce0 = 1'b1;
    end else begin
        reg_file_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_2_0_address0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_0_address0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_2_0_address0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_0_address0;
    end else begin
        reg_file_2_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_2_0_address1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_0_address1 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_address1;
    end else begin
        reg_file_2_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_2_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_2_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_0_ce0;
    end else begin
        reg_file_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_2_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_ce1;
    end else begin
        reg_file_2_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_0_we0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_we0;
    end else begin
        reg_file_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_2_1_address0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_1_address0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_2_1_address0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_1_address0;
    end else begin
        reg_file_2_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_2_1_address1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_1_address1 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_address1;
    end else begin
        reg_file_2_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_2_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_2_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_2_1_ce0;
    end else begin
        reg_file_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_2_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_2_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_ce1;
    end else begin
        reg_file_2_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_2_1_we0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_we0;
    end else begin
        reg_file_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_4_0_address0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_0_address0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_0_address0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_0_address0 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_address0;
    end else begin
        reg_file_4_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_0_address1 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_0_address1 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_0_address1 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_address1;
    end else begin
        reg_file_4_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_4_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_ce0;
    end else begin
        reg_file_4_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_ce1;
    end else begin
        reg_file_4_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_0_d0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_0_d0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_0_d0 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_d0;
    end else begin
        reg_file_4_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_0_we0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_0_we0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_0_we0 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_we0;
    end else begin
        reg_file_4_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_0_we1 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_we1;
    end else begin
        reg_file_4_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_4_1_address0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_1_address0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_1_address0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_1_address0 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_address0;
    end else begin
        reg_file_4_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_1_address1 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_1_address1 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_1_address1 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_address1;
    end else begin
        reg_file_4_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_file_4_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_4_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_ce0;
    end else begin
        reg_file_4_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_ce1;
    end else begin
        reg_file_4_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_1_d0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_1_d0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_1_d0 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_d0;
    end else begin
        reg_file_4_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        reg_file_4_1_we0 = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_reg_file_4_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        reg_file_4_1_we0 = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_reg_file_4_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_1_we0 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_we0;
    end else begin
        reg_file_4_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_4_1_we1 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_we1;
    end else begin
        reg_file_4_1_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_0_address0 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_0_address0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_0_address0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_5_0_address0 = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_address0;
    end else begin
        reg_file_5_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_0_address1 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_0_address1 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_address1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_0_address1 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_address1;
    end else begin
        reg_file_5_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_5_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_ce0;
    end else begin
        reg_file_5_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_ce1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_ce1;
    end else begin
        reg_file_5_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_0_d0 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_0_d0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_0_d0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_5_0_d0 = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_d0;
    end else begin
        reg_file_5_0_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_0_we0 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_0_we0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_0_we0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_0_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_5_0_we0 = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_0_we0;
    end else begin
        reg_file_5_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_1_address0 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_1_address0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_1_address0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_5_1_address0 = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_address0;
    end else begin
        reg_file_5_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_1_address1 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_1_address1 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_address1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_1_address1 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_address1;
    end else begin
        reg_file_5_1_address1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_5_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_ce0;
    end else begin
        reg_file_5_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_ce1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_ce1;
    end else begin
        reg_file_5_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_1_d0 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_1_d0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_1_d0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_d0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_5_1_d0 = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_d0;
    end else begin
        reg_file_5_1_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        reg_file_5_1_we0 = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_reg_file_5_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        reg_file_5_1_we0 = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_reg_file_5_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_5_1_we0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_5_1_we0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        reg_file_5_1_we0 = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_reg_file_5_1_we0;
    end else begin
        reg_file_5_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_6_0_address0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_0_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_0_address0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_address0;
    end else begin
        reg_file_6_0_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_6_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_0_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_0_ce0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_ce0;
    end else begin
        reg_file_6_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_0_ce1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_ce1;
    end else begin
        reg_file_6_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_0_we0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_we0;
    end else begin
        reg_file_6_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_0_we1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_we1;
    end else begin
        reg_file_6_0_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_6_1_address0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_1_address0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_1_address0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_address0;
    end else begin
        reg_file_6_1_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        reg_file_6_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_reg_file_6_1_ce0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_1_ce0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_ce0;
    end else begin
        reg_file_6_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_1_ce1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_ce1;
    end else begin
        reg_file_6_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_1_we0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_we0;
    end else begin
        reg_file_6_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        reg_file_6_1_we1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_we1;
    end else begin
        reg_file_6_1_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            if (((grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            if (((grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state16))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state16;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_done == 1'b0) | (grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_done == 1'b0));
end

assign grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_ap_start_reg;

assign grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start = grp_compute_Pipeline_VITIS_LOOP_140_2_VITIS_LOOP_141_3_fu_76_ap_start_reg;

assign grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start = grp_compute_Pipeline_VITIS_LOOP_150_4_fu_88_ap_start_reg;

assign grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start = grp_compute_Pipeline_VITIS_LOOP_156_5_fu_68_ap_start_reg;

assign grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_ap_start_reg;

assign grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_ap_start_reg;

assign grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start = grp_compute_Pipeline_VITIS_LOOP_181_10_VITIS_LOOP_182_11_fu_122_ap_start_reg;

assign grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start = grp_compute_Pipeline_VITIS_LOOP_190_12_fu_134_ap_start_reg;

assign grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start = grp_compute_Pipeline_VITIS_LOOP_199_13_fu_143_ap_start_reg;

assign reg_file_0_0_address0 = 64'd0;

assign reg_file_2_0_d0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_0_d0;

assign reg_file_2_1_d0 = grp_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7_fu_98_reg_file_2_1_d0;

assign reg_file_4_0_d1 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_0_d1;

assign reg_file_4_1_d1 = grp_compute_Pipeline_VITIS_LOOP_134_1_fu_60_reg_file_4_1_d1;

assign reg_file_6_0_address1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_address1;

assign reg_file_6_0_d0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_d0;

assign reg_file_6_0_d1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_0_d1;

assign reg_file_6_1_address1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_address1;

assign reg_file_6_1_d0 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_d0;

assign reg_file_6_1_d1 = grp_compute_Pipeline_VITIS_LOOP_172_8_VITIS_LOOP_173_9_fu_110_reg_file_6_1_d1;

endmodule //corr_accel_compute
