-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity corr_accel_compute is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    reg_file_0_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_0_0_ce0 : OUT STD_LOGIC;
    reg_file_0_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_0_ce0 : OUT STD_LOGIC;
    reg_file_2_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_0_ce1 : OUT STD_LOGIC;
    reg_file_2_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_1_ce0 : OUT STD_LOGIC;
    reg_file_2_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_1_ce1 : OUT STD_LOGIC;
    reg_file_2_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_3_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_3_0_ce0 : OUT STD_LOGIC;
    reg_file_3_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_3_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_3_1_ce0 : OUT STD_LOGIC;
    reg_file_3_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_0_ce0 : OUT STD_LOGIC;
    reg_file_4_0_we0 : OUT STD_LOGIC;
    reg_file_4_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_0_ce1 : OUT STD_LOGIC;
    reg_file_4_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_1_ce0 : OUT STD_LOGIC;
    reg_file_4_1_we0 : OUT STD_LOGIC;
    reg_file_4_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_1_ce1 : OUT STD_LOGIC;
    reg_file_4_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of corr_accel_compute is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (5 downto 0) := "000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (5 downto 0) := "001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (5 downto 0) := "010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv7_7F : STD_LOGIC_VECTOR (6 downto 0) := "1111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_file_0_0_load_reg_191 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal trunc_ln130_fu_131_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln130_reg_199 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln131_fu_119_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln_fu_144_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal shl_ln_reg_207 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_s_fu_152_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_s_reg_212 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_done : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_idle : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_ready : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_we0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_we0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_done : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_idle : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_ready : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_ce1 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_ce1 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_we0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_ce1 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_we0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_ce1 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_1_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_0_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal i_fu_54 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln131_fu_125_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvars_iv3_fu_58 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln131_1_fu_161_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component corr_accel_compute_Pipeline_VITIS_LOOP_132_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        reg_file_4_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_1_ce0 : OUT STD_LOGIC;
        reg_file_4_1_we0 : OUT STD_LOGIC;
        reg_file_4_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_0_ce0 : OUT STD_LOGIC;
        reg_file_4_0_we0 : OUT STD_LOGIC;
        reg_file_4_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        tmp_36 : IN STD_LOGIC_VECTOR (5 downto 0) );
    end component;


    component corr_accel_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        zext_ln130 : IN STD_LOGIC_VECTOR (5 downto 0);
        shl_ln : IN STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_0_ce0 : OUT STD_LOGIC;
        reg_file_2_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_2_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_0_ce1 : OUT STD_LOGIC;
        reg_file_2_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_2_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_1_ce0 : OUT STD_LOGIC;
        reg_file_2_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_2_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_1_ce1 : OUT STD_LOGIC;
        reg_file_2_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        zext_ln145_2 : IN STD_LOGIC_VECTOR (12 downto 0);
        reg_file_0_0_load : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_1_ce0 : OUT STD_LOGIC;
        reg_file_4_1_we0 : OUT STD_LOGIC;
        reg_file_4_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_1_ce1 : OUT STD_LOGIC;
        reg_file_4_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_0_ce0 : OUT STD_LOGIC;
        reg_file_4_0_we0 : OUT STD_LOGIC;
        reg_file_4_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_0_ce1 : OUT STD_LOGIC;
        reg_file_4_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_3_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_3_1_ce0 : OUT STD_LOGIC;
        reg_file_3_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_3_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_3_0_ce0 : OUT STD_LOGIC;
        reg_file_3_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        tmp_36 : IN STD_LOGIC_VECTOR (5 downto 0) );
    end component;



begin
    grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76 : component corr_accel_compute_Pipeline_VITIS_LOOP_132_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start,
        ap_done => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_done,
        ap_idle => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_idle,
        ap_ready => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_ready,
        reg_file_4_1_address0 => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_address0,
        reg_file_4_1_ce0 => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_ce0,
        reg_file_4_1_we0 => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_we0,
        reg_file_4_1_d0 => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_d0,
        reg_file_4_0_address0 => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_address0,
        reg_file_4_0_ce0 => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_ce0,
        reg_file_4_0_we0 => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_we0,
        reg_file_4_0_d0 => grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_d0,
        tmp_36 => trunc_ln130_reg_199);

    grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85 : component corr_accel_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start,
        ap_done => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_done,
        ap_idle => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_idle,
        ap_ready => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_ready,
        zext_ln130 => trunc_ln130_reg_199,
        shl_ln => shl_ln_reg_207,
        reg_file_2_0_address0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_address0,
        reg_file_2_0_ce0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_ce0,
        reg_file_2_0_q0 => reg_file_2_0_q0,
        reg_file_2_0_address1 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_address1,
        reg_file_2_0_ce1 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_ce1,
        reg_file_2_0_q1 => reg_file_2_0_q1,
        reg_file_2_1_address0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_address0,
        reg_file_2_1_ce0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_ce0,
        reg_file_2_1_q0 => reg_file_2_1_q0,
        reg_file_2_1_address1 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_address1,
        reg_file_2_1_ce1 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_ce1,
        reg_file_2_1_q1 => reg_file_2_1_q1,
        zext_ln145_2 => tmp_s_reg_212,
        reg_file_0_0_load => reg_file_0_0_load_reg_191,
        reg_file_4_1_address0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_address0,
        reg_file_4_1_ce0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_ce0,
        reg_file_4_1_we0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_we0,
        reg_file_4_1_d0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_d0,
        reg_file_4_1_address1 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_address1,
        reg_file_4_1_ce1 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_ce1,
        reg_file_4_1_q1 => reg_file_4_1_q1,
        reg_file_4_0_address0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_address0,
        reg_file_4_0_ce0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_ce0,
        reg_file_4_0_we0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_we0,
        reg_file_4_0_d0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_d0,
        reg_file_4_0_address1 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_address1,
        reg_file_4_0_ce1 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_ce1,
        reg_file_4_0_q1 => reg_file_4_0_q1,
        reg_file_3_1_address0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_1_address0,
        reg_file_3_1_ce0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_1_ce0,
        reg_file_3_1_q0 => reg_file_3_1_q0,
        reg_file_3_0_address0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_0_address0,
        reg_file_3_0_ce0 => grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_0_ce0,
        reg_file_3_0_q0 => reg_file_3_0_q0,
        tmp_36 => trunc_ln130_reg_199);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln131_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_ready = ap_const_logic_1)) then 
                    grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_ready = ap_const_logic_1)) then 
                    grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_54_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_54 <= ap_const_lv7_0;
            elsif (((icmp_ln131_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_fu_54 <= add_ln131_fu_125_p2;
            end if; 
        end if;
    end process;

    indvars_iv3_fu_58_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvars_iv3_fu_58 <= ap_const_lv7_40;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                indvars_iv3_fu_58 <= add_ln131_1_fu_161_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                reg_file_0_0_load_reg_191 <= reg_file_0_0_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                    shl_ln_reg_207(10 downto 5) <= shl_ln_fu_144_p3(10 downto 5);
                    tmp_s_reg_212(12 downto 6) <= tmp_s_fu_152_p3(12 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln131_fu_119_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                trunc_ln130_reg_199 <= trunc_ln130_fu_131_p1;
            end if;
        end if;
    end process;
    shl_ln_reg_207(4 downto 0) <= "00000";
    tmp_s_reg_212(5 downto 0) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln131_fu_119_p2, grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_done, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_done, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln131_fu_119_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXX";
        end case;
    end process;
    add_ln131_1_fu_161_p2 <= std_logic_vector(unsigned(indvars_iv3_fu_58) + unsigned(ap_const_lv7_7F));
    add_ln131_fu_125_p2 <= std_logic_vector(unsigned(i_fu_54) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_done)
    begin
        if ((grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_done)
    begin
        if ((grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln131_fu_119_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((icmp_ln131_fu_119_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln131_fu_119_p2)
    begin
        if (((icmp_ln131_fu_119_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_ap_start_reg;
    grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_ap_start_reg;
    icmp_ln131_fu_119_p2 <= "1" when (i_fu_54 = ap_const_lv7_40) else "0";
    reg_file_0_0_address0 <= ap_const_lv64_0(11 - 1 downto 0);

    reg_file_0_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            reg_file_0_0_ce0 <= ap_const_logic_1;
        else 
            reg_file_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_2_0_address0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_address0;
    reg_file_2_0_address1 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_address1;
    reg_file_2_0_ce0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_ce0;
    reg_file_2_0_ce1 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_0_ce1;
    reg_file_2_1_address0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_address0;
    reg_file_2_1_address1 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_address1;
    reg_file_2_1_ce0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_ce0;
    reg_file_2_1_ce1 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_2_1_ce1;
    reg_file_3_0_address0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_0_address0;
    reg_file_3_0_ce0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_0_ce0;
    reg_file_3_1_address0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_1_address0;
    reg_file_3_1_ce0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_3_1_ce0;

    reg_file_4_0_address0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_address0, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_0_address0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_4_0_address0 <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_address0;
        else 
            reg_file_4_0_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;

    reg_file_4_0_address1 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_address1;

    reg_file_4_0_ce0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_ce0, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_0_ce0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_4_0_ce0 <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_ce0;
        else 
            reg_file_4_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_4_0_ce1_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_0_ce1 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_ce1;
        else 
            reg_file_4_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_4_0_d0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_d0, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_d0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_0_d0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_4_0_d0 <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_d0;
        else 
            reg_file_4_0_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    reg_file_4_0_we0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_we0, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_we0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_0_we0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_0_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_4_0_we0 <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_0_we0;
        else 
            reg_file_4_0_we0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_4_1_address0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_address0, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_address0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_1_address0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_4_1_address0 <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_address0;
        else 
            reg_file_4_1_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;

    reg_file_4_1_address1 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_address1;

    reg_file_4_1_ce0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_ce0, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_ce0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_1_ce0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_4_1_ce0 <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_ce0;
        else 
            reg_file_4_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_4_1_ce1_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_ce1, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_1_ce1 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_ce1;
        else 
            reg_file_4_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_4_1_d0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_d0, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_d0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_1_d0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_4_1_d0 <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_d0;
        else 
            reg_file_4_1_d0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    reg_file_4_1_we0_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_we0, grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_we0, ap_CS_fsm_state4, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            reg_file_4_1_we0 <= grp_compute_Pipeline_VITIS_LOOP_138_3_VITIS_LOOP_141_4_fu_85_reg_file_4_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            reg_file_4_1_we0 <= grp_compute_Pipeline_VITIS_LOOP_132_2_fu_76_reg_file_4_1_we0;
        else 
            reg_file_4_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln_fu_144_p3 <= (trunc_ln130_reg_199 & ap_const_lv5_0);
    tmp_s_fu_152_p3 <= (indvars_iv3_fu_58 & ap_const_lv6_0);
    trunc_ln130_fu_131_p1 <= i_fu_54(6 - 1 downto 0);
end behav;
