// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module corr_accel_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reg_file_4_1_address0,
        reg_file_4_1_ce0,
        reg_file_4_1_q0,
        reg_file_4_0_address0,
        reg_file_4_0_ce0,
        reg_file_4_0_q0,
        reg_file_2_1_address0,
        reg_file_2_1_ce0,
        reg_file_2_1_we0,
        reg_file_2_1_d0,
        reg_file_2_1_address1,
        reg_file_2_1_ce1,
        reg_file_2_1_q1,
        reg_file_2_0_address0,
        reg_file_2_0_ce0,
        reg_file_2_0_we0,
        reg_file_2_0_d0,
        reg_file_2_0_address1,
        reg_file_2_0_ce1,
        reg_file_2_0_q1,
        grp_fu_162_p_din0,
        grp_fu_162_p_din1,
        grp_fu_162_p_dout0,
        grp_fu_162_p_ce,
        grp_fu_166_p_din0,
        grp_fu_166_p_din1,
        grp_fu_166_p_dout0,
        grp_fu_166_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] reg_file_4_1_address0;
output   reg_file_4_1_ce0;
input  [15:0] reg_file_4_1_q0;
output  [10:0] reg_file_4_0_address0;
output   reg_file_4_0_ce0;
input  [15:0] reg_file_4_0_q0;
output  [10:0] reg_file_2_1_address0;
output   reg_file_2_1_ce0;
output   reg_file_2_1_we0;
output  [15:0] reg_file_2_1_d0;
output  [10:0] reg_file_2_1_address1;
output   reg_file_2_1_ce1;
input  [15:0] reg_file_2_1_q1;
output  [10:0] reg_file_2_0_address0;
output   reg_file_2_0_ce0;
output   reg_file_2_0_we0;
output  [15:0] reg_file_2_0_d0;
output  [10:0] reg_file_2_0_address1;
output   reg_file_2_0_ce1;
input  [15:0] reg_file_2_0_q1;
output  [15:0] grp_fu_162_p_din0;
output  [15:0] grp_fu_162_p_din1;
input  [15:0] grp_fu_162_p_dout0;
output   grp_fu_162_p_ce;
output  [15:0] grp_fu_166_p_din0;
output  [15:0] grp_fu_166_p_din1;
input  [15:0] grp_fu_166_p_dout0;
output   grp_fu_166_p_ce;

reg ap_idle;
reg reg_file_4_1_ce0;
reg reg_file_4_0_ce0;
reg reg_file_2_1_ce0;
reg reg_file_2_1_we0;
reg reg_file_2_1_ce1;
reg reg_file_2_0_ce0;
reg reg_file_2_0_we0;
reg reg_file_2_0_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln162_fu_162_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_fu_177_p3;
reg   [0:0] tmp_reg_316;
wire   [4:0] lshr_ln_fu_193_p4;
reg   [4:0] lshr_ln_reg_321;
reg   [10:0] reg_file_2_0_addr_7_reg_336;
reg   [10:0] reg_file_2_0_addr_7_reg_336_pp0_iter2_reg;
reg   [15:0] reg_file_4_0_load_reg_342;
reg   [10:0] reg_file_2_1_addr_7_reg_347;
reg   [10:0] reg_file_2_1_addr_7_reg_347_pp0_iter2_reg;
reg   [15:0] reg_file_4_1_load_reg_353;
wire   [15:0] val2_fu_272_p1;
wire   [15:0] val2_1_fu_286_p1;
wire   [63:0] zext_ln167_fu_203_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln167_1_fu_252_p1;
reg   [6:0] j_7_fu_60;
wire   [6:0] add_ln163_fu_209_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_7_load;
reg   [6:0] i_fu_64;
wire   [6:0] select_ln167_1_fu_234_p3;
reg   [11:0] indvar_flatten6_fu_68;
wire   [11:0] add_ln162_fu_168_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten6_load;
wire   [6:0] select_ln167_fu_185_p3;
wire   [6:0] add_ln162_1_fu_228_p2;
wire   [5:0] trunc_ln167_fu_241_p1;
wire   [10:0] add_ln1_fu_245_p3;
wire   [15:0] bitcast_ln115_fu_263_p1;
wire   [15:0] xor_ln1498_fu_266_p2;
wire   [15:0] bitcast_ln115_1_fu_277_p1;
wire   [15:0] xor_ln1498_1_fu_280_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
reg    ap_block_pp0;
wire    ap_enable_operation_41;
reg    ap_enable_state2_pp0_iter1_stage0;
wire    ap_enable_operation_47;
reg    ap_enable_state3_pp0_iter2_stage0;
wire    ap_enable_operation_62;
reg    ap_enable_state4_pp0_iter3_stage0;
wire    ap_enable_operation_44;
wire    ap_enable_operation_52;
wire    ap_enable_operation_64;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_done_reg = 1'b0;
end

corr_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_64 <= 7'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_64 <= select_ln167_1_fu_234_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln162_fu_162_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_68 <= add_ln162_fu_168_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_68 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln162_fu_162_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_7_fu_60 <= add_ln163_fu_209_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_7_fu_60 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        reg_file_2_0_addr_7_reg_336 <= zext_ln167_1_fu_252_p1;
        reg_file_2_1_addr_7_reg_347 <= zext_ln167_1_fu_252_p1;
        reg_file_4_0_load_reg_342 <= reg_file_4_0_q0;
        reg_file_4_1_load_reg_353 <= reg_file_4_1_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln162_fu_162_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln_reg_321 <= {{select_ln167_fu_185_p3[5:1]}};
        tmp_reg_316 <= ap_sig_allocacmp_j_7_load[32'd6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        reg_file_2_0_addr_7_reg_336_pp0_iter2_reg <= reg_file_2_0_addr_7_reg_336;
        reg_file_2_1_addr_7_reg_347_pp0_iter2_reg <= reg_file_2_1_addr_7_reg_347;
    end
end

always @ (*) begin
    if (((icmp_ln162_fu_162_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_7_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_7_load = j_7_fu_60;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        reg_file_2_0_ce0 = 1'b1;
    end else begin
        reg_file_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_2_0_ce1 = 1'b1;
    end else begin
        reg_file_2_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        reg_file_2_0_we0 = 1'b1;
    end else begin
        reg_file_2_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        reg_file_2_1_ce0 = 1'b1;
    end else begin
        reg_file_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_2_1_ce1 = 1'b1;
    end else begin
        reg_file_2_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        reg_file_2_1_we0 = 1'b1;
    end else begin
        reg_file_2_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_4_0_ce0 = 1'b1;
    end else begin
        reg_file_4_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_4_1_ce0 = 1'b1;
    end else begin
        reg_file_4_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln162_1_fu_228_p2 = (i_fu_64 + 7'd1);

assign add_ln162_fu_168_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 12'd1);

assign add_ln163_fu_209_p2 = (select_ln167_fu_185_p3 + 7'd2);

assign add_ln1_fu_245_p3 = {{trunc_ln167_fu_241_p1}, {lshr_ln_reg_321}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_pp0 = ((ap_ST_fsm_pp0_stage0 == ap_CS_fsm) & (1'b1 == ap_block_pp0_stage0_subdone));
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_operation_41 = (1'b1 == 1'b1);

assign ap_enable_operation_44 = (1'b1 == 1'b1);

assign ap_enable_operation_47 = (1'b1 == 1'b1);

assign ap_enable_operation_52 = (1'b1 == 1'b1);

assign ap_enable_operation_62 = (1'b1 == 1'b1);

assign ap_enable_operation_64 = (1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

always @ (*) begin
    ap_enable_state2_pp0_iter1_stage0 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state3_pp0_iter2_stage0 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_enable_state4_pp0_iter3_stage0 = ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign bitcast_ln115_1_fu_277_p1 = reg_file_4_1_load_reg_353;

assign bitcast_ln115_fu_263_p1 = reg_file_4_0_load_reg_342;

assign grp_fu_162_p_ce = 1'b1;

assign grp_fu_162_p_din0 = reg_file_2_0_q1;

assign grp_fu_162_p_din1 = val2_fu_272_p1;

assign grp_fu_166_p_ce = 1'b1;

assign grp_fu_166_p_din0 = reg_file_2_1_q1;

assign grp_fu_166_p_din1 = val2_1_fu_286_p1;

assign icmp_ln162_fu_162_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 12'd2048) ? 1'b1 : 1'b0);

assign lshr_ln_fu_193_p4 = {{select_ln167_fu_185_p3[5:1]}};

assign reg_file_2_0_address0 = reg_file_2_0_addr_7_reg_336_pp0_iter2_reg;

assign reg_file_2_0_address1 = zext_ln167_1_fu_252_p1;

assign reg_file_2_0_d0 = grp_fu_162_p_dout0;

assign reg_file_2_1_address0 = reg_file_2_1_addr_7_reg_347_pp0_iter2_reg;

assign reg_file_2_1_address1 = zext_ln167_1_fu_252_p1;

assign reg_file_2_1_d0 = grp_fu_166_p_dout0;

assign reg_file_4_0_address0 = zext_ln167_fu_203_p1;

assign reg_file_4_1_address0 = zext_ln167_fu_203_p1;

assign select_ln167_1_fu_234_p3 = ((tmp_reg_316[0:0] == 1'b1) ? add_ln162_1_fu_228_p2 : i_fu_64);

assign select_ln167_fu_185_p3 = ((tmp_fu_177_p3[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_7_load);

assign tmp_fu_177_p3 = ap_sig_allocacmp_j_7_load[32'd6];

assign trunc_ln167_fu_241_p1 = select_ln167_1_fu_234_p3[5:0];

assign val2_1_fu_286_p1 = xor_ln1498_1_fu_280_p2;

assign val2_fu_272_p1 = xor_ln1498_fu_266_p2;

assign xor_ln1498_1_fu_280_p2 = (bitcast_ln115_1_fu_277_p1 ^ 16'd32768);

assign xor_ln1498_fu_266_p2 = (bitcast_ln115_fu_263_p1 ^ 16'd32768);

assign zext_ln167_1_fu_252_p1 = add_ln1_fu_245_p3;

assign zext_ln167_fu_203_p1 = lshr_ln_fu_193_p4;

endmodule //corr_accel_compute_Pipeline_VITIS_LOOP_162_6_VITIS_LOOP_163_7
