// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module corr_accel_compute_Pipeline_VITIS_LOOP_240_20_VITIS_LOOP_241_21 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        reg_file_6_1_address0,
        reg_file_6_1_ce0,
        reg_file_6_1_we0,
        reg_file_6_1_d0,
        reg_file_6_0_address0,
        reg_file_6_0_ce0,
        reg_file_6_0_we0,
        reg_file_6_0_d0,
        reg_file_2_1_address0,
        reg_file_2_1_ce0,
        reg_file_2_1_q0,
        reg_file_2_1_address1,
        reg_file_2_1_ce1,
        reg_file_2_1_q1,
        reg_file_2_0_address0,
        reg_file_2_0_ce0,
        reg_file_2_0_q0,
        reg_file_2_0_address1,
        reg_file_2_0_ce1,
        reg_file_2_0_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [10:0] reg_file_6_1_address0;
output   reg_file_6_1_ce0;
output   reg_file_6_1_we0;
output  [15:0] reg_file_6_1_d0;
output  [10:0] reg_file_6_0_address0;
output   reg_file_6_0_ce0;
output   reg_file_6_0_we0;
output  [15:0] reg_file_6_0_d0;
output  [10:0] reg_file_2_1_address0;
output   reg_file_2_1_ce0;
input  [15:0] reg_file_2_1_q0;
output  [10:0] reg_file_2_1_address1;
output   reg_file_2_1_ce1;
input  [15:0] reg_file_2_1_q1;
output  [10:0] reg_file_2_0_address0;
output   reg_file_2_0_ce0;
input  [15:0] reg_file_2_0_q0;
output  [10:0] reg_file_2_0_address1;
output   reg_file_2_0_ce1;
input  [15:0] reg_file_2_0_q1;

reg ap_idle;
reg reg_file_6_1_ce0;
reg reg_file_6_1_we0;
reg reg_file_6_0_ce0;
reg reg_file_6_0_we0;
reg reg_file_2_1_ce0;
reg reg_file_2_1_ce1;
reg reg_file_2_0_ce0;
reg reg_file_2_0_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln240_fu_170_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] trunc_ln240_fu_232_p1;
reg   [0:0] trunc_ln240_reg_353;
wire    ap_block_pp0_stage0_11001;
wire   [4:0] lshr_ln_fu_236_p4;
reg   [4:0] lshr_ln_reg_359;
wire   [5:0] trunc_ln245_fu_260_p1;
reg   [5:0] trunc_ln245_reg_374;
wire   [63:0] zext_ln245_fu_254_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln245_2_fu_270_p1;
wire   [63:0] zext_ln245_1_fu_313_p1;
reg   [6:0] j_16_fu_64;
wire   [6:0] add_ln241_fu_276_p2;
wire    ap_loop_init;
reg   [6:0] ap_sig_allocacmp_j_16_load;
reg   [6:0] i_fu_68;
wire   [6:0] select_ln240_1_fu_210_p3;
reg   [6:0] ap_sig_allocacmp_i_load;
reg   [11:0] indvar_flatten41_fu_72;
wire   [11:0] add_ln240_fu_176_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten41_load;
wire   [15:0] tmp_s_fu_297_p4;
wire   [15:0] tmp_67_fu_319_p4;
wire   [0:0] tmp_fu_188_p3;
wire   [6:0] add_ln240_1_fu_204_p2;
wire   [4:0] indvars_iv131_udiv_mid2_fu_218_p4;
wire   [6:0] select_ln240_fu_196_p3;
wire   [5:0] zext_ln240_fu_228_p1;
wire   [10:0] add_ln6_fu_246_p3;
wire   [10:0] or_ln245_fu_264_p2;
wire   [10:0] add_ln245_1_fu_307_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

corr_accel_mux_21_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 16 ))
mux_21_16_1_1_U105(
    .din0(reg_file_2_0_q1),
    .din1(reg_file_2_1_q1),
    .din2(trunc_ln240_reg_353),
    .dout(tmp_s_fu_297_p4)
);

corr_accel_mux_21_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 16 ))
mux_21_16_1_1_U106(
    .din0(reg_file_2_0_q0),
    .din1(reg_file_2_1_q0),
    .din2(trunc_ln240_reg_353),
    .dout(tmp_67_fu_319_p4)
);

corr_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln240_fu_170_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_68 <= select_ln240_1_fu_210_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_68 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln240_fu_170_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten41_fu_72 <= add_ln240_fu_176_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten41_fu_72 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln240_fu_170_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_16_fu_64 <= add_ln241_fu_276_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_16_fu_64 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln240_fu_170_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln_reg_359 <= {{select_ln240_fu_196_p3[5:1]}};
        trunc_ln240_reg_353 <= trunc_ln240_fu_232_p1;
        trunc_ln245_reg_374 <= trunc_ln245_fu_260_p1;
    end
end

always @ (*) begin
    if (((icmp_ln240_fu_170_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_load = 7'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_68;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten41_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten41_load = indvar_flatten41_fu_72;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_j_16_load = 7'd0;
    end else begin
        ap_sig_allocacmp_j_16_load = j_16_fu_64;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_2_0_ce0 = 1'b1;
    end else begin
        reg_file_2_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_2_0_ce1 = 1'b1;
    end else begin
        reg_file_2_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_2_1_ce0 = 1'b1;
    end else begin
        reg_file_2_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_2_1_ce1 = 1'b1;
    end else begin
        reg_file_2_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_6_0_ce0 = 1'b1;
    end else begin
        reg_file_6_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_6_0_we0 = 1'b1;
    end else begin
        reg_file_6_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_6_1_ce0 = 1'b1;
    end else begin
        reg_file_6_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        reg_file_6_1_we0 = 1'b1;
    end else begin
        reg_file_6_1_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln240_1_fu_204_p2 = (ap_sig_allocacmp_i_load + 7'd1);

assign add_ln240_fu_176_p2 = (ap_sig_allocacmp_indvar_flatten41_load + 12'd1);

assign add_ln241_fu_276_p2 = (select_ln240_fu_196_p3 + 7'd2);

assign add_ln245_1_fu_307_p3 = {{trunc_ln245_reg_374}, {lshr_ln_reg_359}};

assign add_ln6_fu_246_p3 = {{lshr_ln_fu_236_p4}, {zext_ln240_fu_228_p1}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln240_fu_170_p2 = ((ap_sig_allocacmp_indvar_flatten41_load == 12'd2048) ? 1'b1 : 1'b0);

assign indvars_iv131_udiv_mid2_fu_218_p4 = {{select_ln240_1_fu_210_p3[5:1]}};

assign lshr_ln_fu_236_p4 = {{select_ln240_fu_196_p3[5:1]}};

assign or_ln245_fu_264_p2 = (11'd32 | add_ln6_fu_246_p3);

assign reg_file_2_0_address0 = zext_ln245_2_fu_270_p1;

assign reg_file_2_0_address1 = zext_ln245_fu_254_p1;

assign reg_file_2_1_address0 = zext_ln245_2_fu_270_p1;

assign reg_file_2_1_address1 = zext_ln245_fu_254_p1;

assign reg_file_6_0_address0 = zext_ln245_1_fu_313_p1;

assign reg_file_6_0_d0 = tmp_s_fu_297_p4;

assign reg_file_6_1_address0 = zext_ln245_1_fu_313_p1;

assign reg_file_6_1_d0 = tmp_67_fu_319_p4;

assign select_ln240_1_fu_210_p3 = ((tmp_fu_188_p3[0:0] == 1'b1) ? add_ln240_1_fu_204_p2 : ap_sig_allocacmp_i_load);

assign select_ln240_fu_196_p3 = ((tmp_fu_188_p3[0:0] == 1'b1) ? 7'd0 : ap_sig_allocacmp_j_16_load);

assign tmp_fu_188_p3 = ap_sig_allocacmp_j_16_load[32'd6];

assign trunc_ln240_fu_232_p1 = select_ln240_1_fu_210_p3[0:0];

assign trunc_ln245_fu_260_p1 = select_ln240_1_fu_210_p3[5:0];

assign zext_ln240_fu_228_p1 = indvars_iv131_udiv_mid2_fu_218_p4;

assign zext_ln245_1_fu_313_p1 = add_ln245_1_fu_307_p3;

assign zext_ln245_2_fu_270_p1 = or_ln245_fu_264_p2;

assign zext_ln245_fu_254_p1 = add_ln6_fu_246_p3;

endmodule //corr_accel_compute_Pipeline_VITIS_LOOP_240_20_VITIS_LOOP_241_21
