// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module generic_accel_compute_Pipeline_VITIS_LOOP_9_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        op_assign_reload,
        op_assign_1_reload,
        op_assign_2_reload,
        op_assign_3_reload,
        ret_out,
        ret_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] op_assign_reload;
input  [7:0] op_assign_1_reload;
input  [7:0] op_assign_2_reload;
input  [7:0] op_assign_3_reload;
output  [31:0] ret_out;
output   ret_out_ap_vld;

reg ap_idle;
reg ret_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln9_fu_173_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [2:0] i_6_fu_118;
wire   [2:0] add_ln9_fu_179_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [31:0] ret_fu_122;
wire   [31:0] zext_ln8_3_fu_220_p1;
wire   [31:0] zext_ln8_2_fu_243_p1;
wire   [31:0] zext_ln8_1_fu_266_p1;
wire   [31:0] zext_ln8_fu_299_p1;
wire   [7:0] tmp_2_fu_196_p6;
wire    ap_block_pp0_stage0_01001;
wire   [1:0] tmp_2_fu_196_p5;
wire   [0:0] icmp_ln74_fu_206_p2;
wire   [30:0] empty_35_fu_188_p1;
wire   [30:0] ret_4_fu_212_p3;
wire   [0:0] icmp_ln48_fu_229_p2;
wire   [30:0] ret_3_fu_235_p3;
wire   [0:0] icmp_ln16_fu_252_p2;
wire   [30:0] ret_2_fu_258_p3;
wire   [30:0] tmp_fu_275_p4;
wire   [0:0] icmp_ln88_fu_285_p2;
wire   [30:0] ret_1_fu_291_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
reg    ap_condition_343;
reg    ap_condition_346;
reg    ap_condition_349;
reg    ap_condition_352;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

generic_accel_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U150(
    .din0(op_assign_reload),
    .din1(op_assign_1_reload),
    .din2(op_assign_2_reload),
    .din3(op_assign_3_reload),
    .din4(tmp_2_fu_196_p5),
    .dout(tmp_2_fu_196_p6)
);

generic_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_6_fu_118 <= 3'd0;
        end else if (((icmp_ln9_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_6_fu_118 <= add_ln9_fu_179_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
                        ret_fu_122[0] <= 1'b0;
            ret_fu_122[1] <= 1'b0;
            ret_fu_122[2] <= 1'b0;
            ret_fu_122[3] <= 1'b0;
            ret_fu_122[4] <= 1'b0;
            ret_fu_122[5] <= 1'b0;
            ret_fu_122[6] <= 1'b0;
            ret_fu_122[7] <= 1'b0;
            ret_fu_122[8] <= 1'b0;
            ret_fu_122[9] <= 1'b0;
            ret_fu_122[10] <= 1'b0;
            ret_fu_122[11] <= 1'b0;
            ret_fu_122[12] <= 1'b0;
            ret_fu_122[13] <= 1'b0;
            ret_fu_122[14] <= 1'b0;
            ret_fu_122[15] <= 1'b0;
            ret_fu_122[16] <= 1'b0;
            ret_fu_122[17] <= 1'b0;
            ret_fu_122[18] <= 1'b0;
            ret_fu_122[19] <= 1'b0;
            ret_fu_122[20] <= 1'b0;
            ret_fu_122[21] <= 1'b0;
            ret_fu_122[22] <= 1'b0;
            ret_fu_122[23] <= 1'b0;
            ret_fu_122[24] <= 1'b0;
            ret_fu_122[25] <= 1'b0;
            ret_fu_122[26] <= 1'b0;
            ret_fu_122[27] <= 1'b0;
            ret_fu_122[28] <= 1'b0;
            ret_fu_122[29] <= 1'b0;
            ret_fu_122[30] <= 1'b0;
        end else if ((1'b1 == ap_condition_352)) begin
                        ret_fu_122[30 : 0] <= zext_ln8_fu_299_p1[30 : 0];
        end else if ((1'b1 == ap_condition_349)) begin
                        ret_fu_122[30 : 0] <= zext_ln8_1_fu_266_p1[30 : 0];
        end else if ((1'b1 == ap_condition_346)) begin
                        ret_fu_122[30 : 0] <= zext_ln8_2_fu_243_p1[30 : 0];
        end else if ((1'b1 == ap_condition_343)) begin
                        ret_fu_122[30 : 0] <= zext_ln8_3_fu_220_p1[30 : 0];
        end
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_173_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln9_fu_173_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ret_out_ap_vld = 1'b1;
    end else begin
        ret_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln9_fu_179_p2 = (i_6_fu_118 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_343 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((((((((tmp_2_fu_196_p6 == 8'd23) & (icmp_ln9_fu_173_p2 == 1'd0)) | ((tmp_2_fu_196_p6 == 8'd25) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd20) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd18) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd15) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd12) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd8) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd4) & (icmp_ln9_fu_173_p2 == 1'd0))));
end

always @ (*) begin
    ap_condition_346 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((((((((((((((((tmp_2_fu_196_p6 == 8'd28) & (icmp_ln9_fu_173_p2 == 1'd0)) | ((tmp_2_fu_196_p6 == 8'd29) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd27) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd26) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd24) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd22) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd17) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd16) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd14) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd11) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd10) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd7) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd6) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd3) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd2) & (icmp_ln9_fu_173_p2 == 1'd0))));
end

always @ (*) begin
    ap_condition_349 = ((tmp_2_fu_196_p6 == 8'd1) & (icmp_ln9_fu_173_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_352 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((((((tmp_2_fu_196_p6 == 8'd13) & (icmp_ln9_fu_173_p2 == 1'd0)) | ((tmp_2_fu_196_p6 == 8'd19) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd9) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd5) & (icmp_ln9_fu_173_p2 == 1'd0))) | ((tmp_2_fu_196_p6 == 8'd21) & (icmp_ln9_fu_173_p2 == 1'd0))));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign empty_35_fu_188_p1 = ret_fu_122[30:0];

assign icmp_ln16_fu_252_p2 = (($signed(ret_fu_122) > $signed(32'd262144)) ? 1'b1 : 1'b0);

assign icmp_ln48_fu_229_p2 = (($signed(ret_fu_122) > $signed(32'd4096)) ? 1'b1 : 1'b0);

assign icmp_ln74_fu_206_p2 = (($signed(ret_fu_122) > $signed(32'd64)) ? 1'b1 : 1'b0);

assign icmp_ln88_fu_285_p2 = (($signed(tmp_fu_275_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln9_fu_173_p2 = ((i_6_fu_118 == 3'd4) ? 1'b1 : 1'b0);

assign ret_1_fu_291_p3 = ((icmp_ln88_fu_285_p2[0:0] == 1'b1) ? empty_35_fu_188_p1 : 31'd1);

assign ret_2_fu_258_p3 = ((icmp_ln16_fu_252_p2[0:0] == 1'b1) ? empty_35_fu_188_p1 : 31'd262144);

assign ret_3_fu_235_p3 = ((icmp_ln48_fu_229_p2[0:0] == 1'b1) ? empty_35_fu_188_p1 : 31'd4096);

assign ret_4_fu_212_p3 = ((icmp_ln74_fu_206_p2[0:0] == 1'b1) ? empty_35_fu_188_p1 : 31'd64);

assign ret_out = ret_fu_122;

assign tmp_2_fu_196_p5 = i_6_fu_118[1:0];

assign tmp_fu_275_p4 = {{ret_fu_122[31:1]}};

assign zext_ln8_1_fu_266_p1 = ret_2_fu_258_p3;

assign zext_ln8_2_fu_243_p1 = ret_3_fu_235_p3;

assign zext_ln8_3_fu_220_p1 = ret_4_fu_212_p3;

assign zext_ln8_fu_299_p1 = ret_1_fu_291_p3;

always @ (posedge ap_clk) begin
    ret_fu_122[31] <= 1'b0;
end

endmodule //generic_accel_compute_Pipeline_VITIS_LOOP_9_1
