-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity corr_accel_compute_Pipeline_VITIS_LOOP_139_3_VITIS_LOOP_141_4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    i : IN STD_LOGIC_VECTOR (5 downto 0);
    reg_file_2_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_0_ce0 : OUT STD_LOGIC;
    reg_file_2_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_0_ce1 : OUT STD_LOGIC;
    reg_file_2_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_1_ce0 : OUT STD_LOGIC;
    reg_file_2_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_1_ce1 : OUT STD_LOGIC;
    reg_file_2_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_0_0_load : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_1_ce0 : OUT STD_LOGIC;
    reg_file_4_1_we0 : OUT STD_LOGIC;
    reg_file_4_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_1_ce1 : OUT STD_LOGIC;
    reg_file_4_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_0_ce0 : OUT STD_LOGIC;
    reg_file_4_0_we0 : OUT STD_LOGIC;
    reg_file_4_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_0_ce1 : OUT STD_LOGIC;
    reg_file_4_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_3_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_3_1_ce0 : OUT STD_LOGIC;
    reg_file_3_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_3_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_3_0_ce0 : OUT STD_LOGIC;
    reg_file_3_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_172_p_din0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_172_p_din1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_172_p_dout0 : IN STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_172_p_ce : OUT STD_LOGIC;
    grp_fu_176_p_din0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_176_p_din1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_176_p_dout0 : IN STD_LOGIC_VECTOR (15 downto 0);
    grp_fu_176_p_ce : OUT STD_LOGIC );
end;


architecture behav of corr_accel_compute_Pipeline_VITIS_LOOP_139_3_VITIS_LOOP_141_4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv7_2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln139_fu_283_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln140_fu_279_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln140_reg_484 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln139_reg_500 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_504 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln140_1_fu_344_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln140_1_reg_510 : STD_LOGIC_VECTOR (0 downto 0);
    signal lshr_ln8_reg_526 : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln8_reg_526_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln8_reg_526_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal lshr_ln8_reg_526_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_reg_532 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_4_reg_532_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln139_1_fu_415_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln139_2_fu_423_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln139_2_reg_542 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_mid2_reg_547 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul2_reg_573 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_file_4_0_addr_reg_578 : STD_LOGIC_VECTOR (10 downto 0);
    signal reg_file_4_0_addr_reg_578_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_229_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul28_1_reg_584 : STD_LOGIC_VECTOR (15 downto 0);
    signal reg_file_4_1_addr_reg_589 : STD_LOGIC_VECTOR (10 downto 0);
    signal reg_file_4_1_addr_reg_589_pp0_iter5_reg : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal zext_ln140_fu_273_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln140_1_fu_338_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln145_fu_435_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln145_1_fu_447_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_74 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln141_fu_376_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (6 downto 0);
    signal k_fu_78 : STD_LOGIC_VECTOR (6 downto 0);
    signal select_ln139_3_fu_348_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_k_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal indvar_flatten_fu_82 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln139_fu_289_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_208_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_214_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln7_fu_255_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln1_fu_265_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln139_1_fu_314_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal lshr_ln140_mid1_fu_320_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln1_mid1_fu_330_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln139_fu_306_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_mid1_fu_406_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_fu_397_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln2_fu_428_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln145_1_fu_441_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0 : BOOLEAN;
    signal ap_enable_operation_81 : BOOLEAN;
    signal ap_enable_state5_pp0_iter4_stage0 : BOOLEAN;
    signal ap_enable_operation_85 : BOOLEAN;
    signal ap_enable_state6_pp0_iter5_stage0 : BOOLEAN;
    signal ap_enable_operation_94 : BOOLEAN;
    signal ap_enable_state7_pp0_iter6_stage0 : BOOLEAN;
    signal ap_enable_operation_84 : BOOLEAN;
    signal ap_enable_operation_87 : BOOLEAN;
    signal ap_enable_operation_96 : BOOLEAN;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component corr_accel_hadd_16ns_16ns_16_2_full_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component corr_accel_hmul_16ns_16ns_16_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component corr_accel_mux_21_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component corr_accel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    hadd_16ns_16ns_16_2_full_dsp_1_U43 : component corr_accel_hadd_16ns_16ns_16_2_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_file_4_0_q1,
        din1 => mul2_reg_573,
        ce => ap_const_logic_1,
        dout => grp_fu_208_p2);

    hadd_16ns_16ns_16_2_full_dsp_1_U44 : component corr_accel_hadd_16ns_16ns_16_2_full_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => reg_file_4_1_q1,
        din1 => mul28_1_reg_584,
        ce => ap_const_logic_1,
        dout => grp_fu_214_p2);

    hmul_16ns_16ns_16_2_max_dsp_1_U47 : component corr_accel_hmul_16ns_16ns_16_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_1_mid2_reg_547,
        din1 => reg_file_3_1_q0,
        ce => ap_const_logic_1,
        dout => grp_fu_229_p2);

    mux_21_16_1_1_U48 : component corr_accel_mux_21_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 1,
        dout_WIDTH => 16)
    port map (
        din0 => reg_file_2_0_q1,
        din1 => reg_file_2_1_q1,
        din2 => trunc_ln140_reg_484,
        dout => tmp_fu_397_p4);

    mux_21_16_1_1_U49 : component corr_accel_mux_21_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 1,
        dout_WIDTH => 16)
    port map (
        din0 => reg_file_2_0_q0,
        din1 => reg_file_2_1_q0,
        din2 => trunc_ln140_1_reg_510,
        dout => tmp_mid1_fu_406_p4);

    flow_control_loop_pipe_sequential_init_U : component corr_accel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten_fu_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln139_fu_283_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten_fu_82 <= add_ln139_fu_289_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_82 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln139_fu_283_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_74 <= add_ln141_fu_376_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_74 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    k_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln139_fu_283_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    k_fu_78 <= select_ln139_3_fu_348_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    k_fu_78 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln139_reg_500 <= icmp_ln139_fu_283_p2;
                lshr_ln8_reg_526_pp0_iter1_reg <= lshr_ln8_reg_526;
                tmp_4_reg_532_pp0_iter1_reg <= tmp_4_reg_532;
                trunc_ln140_reg_484 <= trunc_ln140_fu_279_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                lshr_ln8_reg_526_pp0_iter2_reg <= lshr_ln8_reg_526_pp0_iter1_reg;
                lshr_ln8_reg_526_pp0_iter3_reg <= lshr_ln8_reg_526_pp0_iter2_reg;
                mul28_1_reg_584 <= grp_fu_229_p2;
                mul2_reg_573 <= grp_fu_176_p_dout0;
                reg_file_4_0_addr_reg_578 <= zext_ln145_1_fu_447_p1(11 - 1 downto 0);
                reg_file_4_0_addr_reg_578_pp0_iter5_reg <= reg_file_4_0_addr_reg_578;
                reg_file_4_1_addr_reg_589 <= zext_ln145_1_fu_447_p1(11 - 1 downto 0);
                reg_file_4_1_addr_reg_589_pp0_iter5_reg <= reg_file_4_1_addr_reg_589;
                tmp_1_mid2_reg_547 <= grp_fu_172_p_dout0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln139_fu_283_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                lshr_ln8_reg_526 <= select_ln139_fu_306_p3(5 downto 1);
                tmp_1_reg_504 <= ap_sig_allocacmp_j_load(6 downto 6);
                tmp_4_reg_532 <= select_ln139_3_fu_348_p3(5 downto 1);
                trunc_ln140_1_reg_510 <= trunc_ln140_1_fu_344_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln139_reg_500 = ap_const_lv1_0))) then
                select_ln139_2_reg_542 <= select_ln139_2_fu_423_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln139_1_fu_314_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k_1) + unsigned(ap_const_lv7_1));
    add_ln139_fu_289_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv12_1));
    add_ln141_fu_376_p2 <= std_logic_vector(unsigned(select_ln139_fu_306_p3) + unsigned(ap_const_lv7_2));
    add_ln145_1_fu_441_p3 <= (i & lshr_ln8_reg_526_pp0_iter3_reg);
    add_ln1_fu_265_p3 <= (i & lshr_ln7_fu_255_p4);
    add_ln1_mid1_fu_330_p3 <= (i & lshr_ln140_mid1_fu_320_p4);
    add_ln2_fu_428_p4 <= ((tmp_4_reg_532_pp0_iter1_reg & select_ln139_2_reg_542) & lshr_ln8_reg_526_pp0_iter1_reg);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);

    ap_block_pp0_assign_proc : process(ap_CS_fsm, ap_block_pp0_stage0_subdone)
    begin
                ap_block_pp0 <= ((ap_ST_fsm_pp0_stage0 = ap_CS_fsm) and (ap_const_boolean_1 = ap_block_pp0_stage0_subdone));
    end process;

        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln139_fu_283_p2)
    begin
        if (((icmp_ln139_fu_283_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln139_reg_500)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln139_reg_500 = ap_const_lv1_1))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter5_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter5_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

        ap_enable_operation_81 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_84 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_85 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_87 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_94 <= (ap_const_boolean_1 = ap_const_boolean_1);
        ap_enable_operation_96 <= (ap_const_boolean_1 = ap_const_boolean_1);
    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_enable_state5_pp0_iter4_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter4)
    begin
                ap_enable_state5_pp0_iter4_stage0 <= ((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state6_pp0_iter5_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter5)
    begin
                ap_enable_state6_pp0_iter5_stage0 <= ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_enable_state7_pp0_iter6_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter6)
    begin
                ap_enable_state7_pp0_iter6_stage0 <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_82)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_82;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_74, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_74;
        end if; 
    end process;


    ap_sig_allocacmp_k_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, k_fu_78)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_k_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_k_1 <= k_fu_78;
        end if; 
    end process;

    grp_fu_172_p_ce <= ap_const_logic_1;
    grp_fu_172_p_din0 <= reg_file_0_0_load;
    grp_fu_172_p_din1 <= select_ln139_1_fu_415_p3;
    grp_fu_176_p_ce <= ap_const_logic_1;
    grp_fu_176_p_din0 <= tmp_1_mid2_reg_547;
    grp_fu_176_p_din1 <= reg_file_3_0_q0;
    icmp_ln139_fu_283_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv12_800) else "0";
    lshr_ln140_mid1_fu_320_p4 <= add_ln139_1_fu_314_p2(5 downto 1);
    lshr_ln7_fu_255_p4 <= ap_sig_allocacmp_k_1(5 downto 1);
    reg_file_2_0_address0 <= zext_ln140_1_fu_338_p1(11 - 1 downto 0);
    reg_file_2_0_address1 <= zext_ln140_fu_273_p1(11 - 1 downto 0);

    reg_file_2_0_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            reg_file_2_0_ce0 <= ap_const_logic_1;
        else 
            reg_file_2_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_2_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            reg_file_2_0_ce1 <= ap_const_logic_1;
        else 
            reg_file_2_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_2_1_address0 <= zext_ln140_1_fu_338_p1(11 - 1 downto 0);
    reg_file_2_1_address1 <= zext_ln140_fu_273_p1(11 - 1 downto 0);

    reg_file_2_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            reg_file_2_1_ce0 <= ap_const_logic_1;
        else 
            reg_file_2_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_2_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            reg_file_2_1_ce1 <= ap_const_logic_1;
        else 
            reg_file_2_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_3_0_address0 <= zext_ln145_fu_435_p1(11 - 1 downto 0);

    reg_file_3_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            reg_file_3_0_ce0 <= ap_const_logic_1;
        else 
            reg_file_3_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_3_1_address0 <= zext_ln145_fu_435_p1(11 - 1 downto 0);

    reg_file_3_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            reg_file_3_1_ce0 <= ap_const_logic_1;
        else 
            reg_file_3_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_4_0_address0 <= reg_file_4_0_addr_reg_578_pp0_iter5_reg;
    reg_file_4_0_address1 <= zext_ln145_1_fu_447_p1(11 - 1 downto 0);

    reg_file_4_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            reg_file_4_0_ce0 <= ap_const_logic_1;
        else 
            reg_file_4_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_4_0_ce1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            reg_file_4_0_ce1 <= ap_const_logic_1;
        else 
            reg_file_4_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_4_0_d0 <= grp_fu_208_p2;

    reg_file_4_0_we0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            reg_file_4_0_we0 <= ap_const_logic_1;
        else 
            reg_file_4_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_4_1_address0 <= reg_file_4_1_addr_reg_589_pp0_iter5_reg;
    reg_file_4_1_address1 <= zext_ln145_1_fu_447_p1(11 - 1 downto 0);

    reg_file_4_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            reg_file_4_1_ce0 <= ap_const_logic_1;
        else 
            reg_file_4_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    reg_file_4_1_ce1_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            reg_file_4_1_ce1 <= ap_const_logic_1;
        else 
            reg_file_4_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_4_1_d0 <= grp_fu_214_p2;

    reg_file_4_1_we0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            reg_file_4_1_we0 <= ap_const_logic_1;
        else 
            reg_file_4_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    select_ln139_1_fu_415_p3 <= 
        tmp_mid1_fu_406_p4 when (tmp_1_reg_504(0) = '1') else 
        tmp_fu_397_p4;
    select_ln139_2_fu_423_p3 <= 
        trunc_ln140_1_reg_510 when (tmp_1_reg_504(0) = '1') else 
        trunc_ln140_reg_484;
    select_ln139_3_fu_348_p3 <= 
        add_ln139_1_fu_314_p2 when (tmp_1_fu_298_p3(0) = '1') else 
        ap_sig_allocacmp_k_1;
    select_ln139_fu_306_p3 <= 
        ap_const_lv7_0 when (tmp_1_fu_298_p3(0) = '1') else 
        ap_sig_allocacmp_j_load;
    tmp_1_fu_298_p3 <= ap_sig_allocacmp_j_load(6 downto 6);
    trunc_ln140_1_fu_344_p1 <= add_ln139_1_fu_314_p2(1 - 1 downto 0);
    trunc_ln140_fu_279_p1 <= ap_sig_allocacmp_k_1(1 - 1 downto 0);
    zext_ln140_1_fu_338_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1_mid1_fu_330_p3),64));
    zext_ln140_fu_273_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln1_fu_265_p3),64));
    zext_ln145_1_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln145_1_fu_441_p3),64));
    zext_ln145_fu_435_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln2_fu_428_p4),64));
end behav;
