-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity corr_accel_compute is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    reg_file_0_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_0_0_ce0 : OUT STD_LOGIC;
    reg_file_0_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_0_ce0 : OUT STD_LOGIC;
    reg_file_4_0_we0 : OUT STD_LOGIC;
    reg_file_4_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_0_ce1 : OUT STD_LOGIC;
    reg_file_4_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_1_ce0 : OUT STD_LOGIC;
    reg_file_4_1_we0 : OUT STD_LOGIC;
    reg_file_4_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_1_ce1 : OUT STD_LOGIC;
    reg_file_4_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_6_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_6_0_ce0 : OUT STD_LOGIC;
    reg_file_6_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_6_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_6_1_ce0 : OUT STD_LOGIC;
    reg_file_6_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_7_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_7_0_ce0 : OUT STD_LOGIC;
    reg_file_7_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
    reg_file_7_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_7_1_ce0 : OUT STD_LOGIC;
    reg_file_7_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of corr_accel_compute is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_40 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_file_0_0_load_reg_201 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln132_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln136_fu_170_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln136_reg_219 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_179_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal grp_fu_110_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_1_reg_229 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_done : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_idle : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_ready : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_1_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_0_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_we0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_ce1 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_ce0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_we0 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_ce1 : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_din0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_din1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_ce : STD_LOGIC;
    signal grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal zext_ln136_fu_164_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_66 : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln132_fu_148_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_110_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_110_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal lshr_ln_fu_154_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_fu_110_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component corr_accel_compute_Pipeline_VITIS_LOOP_137_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        reg_file_6_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_6_1_ce0 : OUT STD_LOGIC;
        reg_file_6_1_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_6_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_6_0_ce0 : OUT STD_LOGIC;
        reg_file_6_0_q0 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_1_ce0 : OUT STD_LOGIC;
        reg_file_4_1_we0 : OUT STD_LOGIC;
        reg_file_4_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_1_ce1 : OUT STD_LOGIC;
        reg_file_4_1_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_0_ce0 : OUT STD_LOGIC;
        reg_file_4_0_we0 : OUT STD_LOGIC;
        reg_file_4_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_0_ce1 : OUT STD_LOGIC;
        reg_file_4_0_q1 : IN STD_LOGIC_VECTOR (15 downto 0);
        tmp_1 : IN STD_LOGIC_VECTOR (15 downto 0);
        grp_fu_110_p_din0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        grp_fu_110_p_din1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        grp_fu_110_p_dout0 : IN STD_LOGIC_VECTOR (15 downto 0);
        grp_fu_110_p_ce : OUT STD_LOGIC );
    end component;


    component corr_accel_hmul_16ns_16ns_16_2_max_dsp_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component corr_accel_mux_21_16_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (15 downto 0);
        din2 : IN STD_LOGIC_VECTOR (0 downto 0);
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121 : component corr_accel_compute_Pipeline_VITIS_LOOP_137_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start,
        ap_done => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_done,
        ap_idle => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_idle,
        ap_ready => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_ready,
        reg_file_6_1_address0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_1_address0,
        reg_file_6_1_ce0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_1_ce0,
        reg_file_6_1_q0 => reg_file_6_1_q0,
        reg_file_6_0_address0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_0_address0,
        reg_file_6_0_ce0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_0_ce0,
        reg_file_6_0_q0 => reg_file_6_0_q0,
        reg_file_4_1_address0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_address0,
        reg_file_4_1_ce0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_ce0,
        reg_file_4_1_we0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_we0,
        reg_file_4_1_d0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_d0,
        reg_file_4_1_address1 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_address1,
        reg_file_4_1_ce1 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_ce1,
        reg_file_4_1_q1 => reg_file_4_1_q1,
        reg_file_4_0_address0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_address0,
        reg_file_4_0_ce0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_ce0,
        reg_file_4_0_we0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_we0,
        reg_file_4_0_d0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_d0,
        reg_file_4_0_address1 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_address1,
        reg_file_4_0_ce1 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_ce1,
        reg_file_4_0_q1 => reg_file_4_0_q1,
        tmp_1 => tmp_1_reg_229,
        grp_fu_110_p_din0 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_din0,
        grp_fu_110_p_din1 => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_din1,
        grp_fu_110_p_dout0 => grp_fu_110_p2,
        grp_fu_110_p_ce => grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_ce);

    hmul_16ns_16ns_16_2_max_dsp_1_U48 : component corr_accel_hmul_16ns_16ns_16_2_max_dsp_1
    generic map (
        ID => 1,
        NUM_STAGE => 2,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_110_p0,
        din1 => grp_fu_110_p1,
        ce => grp_fu_110_ce,
        dout => grp_fu_110_p2);

    mux_21_16_1_1_U49 : component corr_accel_mux_21_16_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 16,
        din2_WIDTH => 1,
        dout_WIDTH => 16)
    port map (
        din0 => reg_file_7_0_q0,
        din1 => reg_file_7_1_q0,
        din2 => trunc_ln136_reg_219,
        dout => tmp_fu_179_p4);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_ready = ap_const_logic_1)) then 
                    grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    j_fu_66_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                j_fu_66 <= ap_const_lv7_0;
            elsif (((icmp_ln132_fu_142_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                j_fu_66 <= add_ln132_fu_148_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                reg_file_0_0_load_reg_201 <= reg_file_0_0_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                tmp_1_reg_229 <= grp_fu_110_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln132_fu_142_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                trunc_ln136_reg_219 <= trunc_ln136_fu_170_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln132_fu_142_p2, grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_done, ap_CS_fsm_state7)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln132_fu_142_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln132_fu_148_p2 <= std_logic_vector(unsigned(j_fu_66) + unsigned(ap_const_lv7_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_done)
    begin
        if ((grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln132_fu_142_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((icmp_ln132_fu_142_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, icmp_ln132_fu_142_p2)
    begin
        if (((icmp_ln132_fu_142_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_ap_start_reg;

    grp_fu_110_ce_assign_proc : process(grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_ce, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_110_ce <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_ce;
        else 
            grp_fu_110_ce <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_110_p0_assign_proc : process(reg_file_0_0_load_reg_201, ap_CS_fsm_state4, grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_din0, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_110_p0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_din0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_110_p0 <= reg_file_0_0_load_reg_201;
        else 
            grp_fu_110_p0 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;


    grp_fu_110_p1_assign_proc : process(tmp_fu_179_p4, ap_CS_fsm_state4, grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_din1, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            grp_fu_110_p1 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_grp_fu_110_p_din1;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            grp_fu_110_p1 <= tmp_fu_179_p4;
        else 
            grp_fu_110_p1 <= "XXXXXXXXXXXXXXXX";
        end if; 
    end process;

    icmp_ln132_fu_142_p2 <= "1" when (j_fu_66 = ap_const_lv7_40) else "0";
    lshr_ln_fu_154_p4 <= j_fu_66(5 downto 1);
    reg_file_0_0_address0 <= ap_const_lv64_0(11 - 1 downto 0);

    reg_file_0_0_ce0_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            reg_file_0_0_ce0 <= ap_const_logic_1;
        else 
            reg_file_0_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_4_0_address0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_address0;
    reg_file_4_0_address1 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_address1;
    reg_file_4_0_ce0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_ce0;
    reg_file_4_0_ce1 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_ce1;
    reg_file_4_0_d0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_d0;
    reg_file_4_0_we0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_0_we0;
    reg_file_4_1_address0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_address0;
    reg_file_4_1_address1 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_address1;
    reg_file_4_1_ce0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_ce0;
    reg_file_4_1_ce1 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_ce1;
    reg_file_4_1_d0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_d0;
    reg_file_4_1_we0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_4_1_we0;
    reg_file_6_0_address0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_0_address0;
    reg_file_6_0_ce0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_0_ce0;
    reg_file_6_1_address0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_1_address0;
    reg_file_6_1_ce0 <= grp_compute_Pipeline_VITIS_LOOP_137_2_fu_121_reg_file_6_1_ce0;
    reg_file_7_0_address0 <= zext_ln136_fu_164_p1(11 - 1 downto 0);

    reg_file_7_0_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            reg_file_7_0_ce0 <= ap_const_logic_1;
        else 
            reg_file_7_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    reg_file_7_1_address0 <= zext_ln136_fu_164_p1(11 - 1 downto 0);

    reg_file_7_1_ce0_assign_proc : process(ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            reg_file_7_1_ce0 <= ap_const_logic_1;
        else 
            reg_file_7_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln136_fu_170_p1 <= j_fu_66(1 - 1 downto 0);
    zext_ln136_fu_164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_154_p4),64));
end behav;
