-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity corr_accel_recv_data_burst is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_data_AWVALID : OUT STD_LOGIC;
    m_axi_data_AWREADY : IN STD_LOGIC;
    m_axi_data_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_data_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_WVALID : OUT STD_LOGIC;
    m_axi_data_WREADY : IN STD_LOGIC;
    m_axi_data_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_data_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_data_WLAST : OUT STD_LOGIC;
    m_axi_data_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_ARVALID : OUT STD_LOGIC;
    m_axi_data_ARREADY : IN STD_LOGIC;
    m_axi_data_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_data_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_data_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_data_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_data_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_RVALID : IN STD_LOGIC;
    m_axi_data_RREADY : OUT STD_LOGIC;
    m_axi_data_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    m_axi_data_RLAST : IN STD_LOGIC;
    m_axi_data_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_data_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_BVALID : IN STD_LOGIC;
    m_axi_data_BREADY : OUT STD_LOGIC;
    m_axi_data_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_data_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_data_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    data_in : IN STD_LOGIC_VECTOR (63 downto 0);
    reg_file_0_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_0_0_ce0 : OUT STD_LOGIC;
    reg_file_0_0_we0 : OUT STD_LOGIC;
    reg_file_0_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_0_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_0_0_ce1 : OUT STD_LOGIC;
    reg_file_0_0_we1 : OUT STD_LOGIC;
    reg_file_0_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_0_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_0_1_ce0 : OUT STD_LOGIC;
    reg_file_0_1_we0 : OUT STD_LOGIC;
    reg_file_0_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_0_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_0_1_ce1 : OUT STD_LOGIC;
    reg_file_0_1_we1 : OUT STD_LOGIC;
    reg_file_0_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_1_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_1_0_ce0 : OUT STD_LOGIC;
    reg_file_1_0_we0 : OUT STD_LOGIC;
    reg_file_1_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_1_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_1_0_ce1 : OUT STD_LOGIC;
    reg_file_1_0_we1 : OUT STD_LOGIC;
    reg_file_1_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_1_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_1_1_ce0 : OUT STD_LOGIC;
    reg_file_1_1_we0 : OUT STD_LOGIC;
    reg_file_1_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_1_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_1_1_ce1 : OUT STD_LOGIC;
    reg_file_1_1_we1 : OUT STD_LOGIC;
    reg_file_1_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_0_ce0 : OUT STD_LOGIC;
    reg_file_2_0_we0 : OUT STD_LOGIC;
    reg_file_2_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_0_ce1 : OUT STD_LOGIC;
    reg_file_2_0_we1 : OUT STD_LOGIC;
    reg_file_2_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_1_ce0 : OUT STD_LOGIC;
    reg_file_2_1_we0 : OUT STD_LOGIC;
    reg_file_2_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_2_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_2_1_ce1 : OUT STD_LOGIC;
    reg_file_2_1_we1 : OUT STD_LOGIC;
    reg_file_2_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_3_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_3_0_ce0 : OUT STD_LOGIC;
    reg_file_3_0_we0 : OUT STD_LOGIC;
    reg_file_3_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_3_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_3_0_ce1 : OUT STD_LOGIC;
    reg_file_3_0_we1 : OUT STD_LOGIC;
    reg_file_3_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_3_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_3_1_ce0 : OUT STD_LOGIC;
    reg_file_3_1_we0 : OUT STD_LOGIC;
    reg_file_3_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_3_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_3_1_ce1 : OUT STD_LOGIC;
    reg_file_3_1_we1 : OUT STD_LOGIC;
    reg_file_3_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_0_ce0 : OUT STD_LOGIC;
    reg_file_4_0_we0 : OUT STD_LOGIC;
    reg_file_4_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_0_ce1 : OUT STD_LOGIC;
    reg_file_4_0_we1 : OUT STD_LOGIC;
    reg_file_4_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_1_ce0 : OUT STD_LOGIC;
    reg_file_4_1_we0 : OUT STD_LOGIC;
    reg_file_4_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_4_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_4_1_ce1 : OUT STD_LOGIC;
    reg_file_4_1_we1 : OUT STD_LOGIC;
    reg_file_4_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_5_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_5_0_ce0 : OUT STD_LOGIC;
    reg_file_5_0_we0 : OUT STD_LOGIC;
    reg_file_5_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_5_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_5_0_ce1 : OUT STD_LOGIC;
    reg_file_5_0_we1 : OUT STD_LOGIC;
    reg_file_5_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_5_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_5_1_ce0 : OUT STD_LOGIC;
    reg_file_5_1_we0 : OUT STD_LOGIC;
    reg_file_5_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_5_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_5_1_ce1 : OUT STD_LOGIC;
    reg_file_5_1_we1 : OUT STD_LOGIC;
    reg_file_5_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_6_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_6_0_ce0 : OUT STD_LOGIC;
    reg_file_6_0_we0 : OUT STD_LOGIC;
    reg_file_6_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_6_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_6_0_ce1 : OUT STD_LOGIC;
    reg_file_6_0_we1 : OUT STD_LOGIC;
    reg_file_6_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_6_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_6_1_ce0 : OUT STD_LOGIC;
    reg_file_6_1_we0 : OUT STD_LOGIC;
    reg_file_6_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_6_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_6_1_ce1 : OUT STD_LOGIC;
    reg_file_6_1_we1 : OUT STD_LOGIC;
    reg_file_6_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_7_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_7_0_ce0 : OUT STD_LOGIC;
    reg_file_7_0_we0 : OUT STD_LOGIC;
    reg_file_7_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_7_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_7_0_ce1 : OUT STD_LOGIC;
    reg_file_7_0_we1 : OUT STD_LOGIC;
    reg_file_7_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_7_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_7_1_ce0 : OUT STD_LOGIC;
    reg_file_7_1_we0 : OUT STD_LOGIC;
    reg_file_7_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    reg_file_7_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
    reg_file_7_1_ce1 : OUT STD_LOGIC;
    reg_file_7_1_we1 : OUT STD_LOGIC;
    reg_file_7_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of corr_accel_recv_data_burst is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_2000 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000010000000000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal data_blk_n_AR : STD_LOGIC;
    signal trunc_ln_fu_126_p4 : STD_LOGIC_VECTOR (60 downto 0);
    signal trunc_ln_reg_147 : STD_LOGIC_VECTOR (60 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_idle : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_ready : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWVALID : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WVALID : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WSTRB : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WLAST : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARVALID : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_RREADY : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_BREADY : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_ce0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_we0 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_d0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_ce1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_we1 : STD_LOGIC;
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_d1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal sext_ln39_fu_136_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component corr_accel_recv_data_burst_Pipeline_VITIS_LOOP_39_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_data_AWVALID : OUT STD_LOGIC;
        m_axi_data_AWREADY : IN STD_LOGIC;
        m_axi_data_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_data_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_data_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_data_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_data_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_data_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_data_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_data_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_data_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_data_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_WVALID : OUT STD_LOGIC;
        m_axi_data_WREADY : IN STD_LOGIC;
        m_axi_data_WDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_data_WSTRB : OUT STD_LOGIC_VECTOR (7 downto 0);
        m_axi_data_WLAST : OUT STD_LOGIC;
        m_axi_data_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_ARVALID : OUT STD_LOGIC;
        m_axi_data_ARREADY : IN STD_LOGIC;
        m_axi_data_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_data_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_data_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_data_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_data_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_data_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_data_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_data_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_data_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_data_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_RVALID : IN STD_LOGIC;
        m_axi_data_RREADY : OUT STD_LOGIC;
        m_axi_data_RDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        m_axi_data_RLAST : IN STD_LOGIC;
        m_axi_data_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_data_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_data_BVALID : IN STD_LOGIC;
        m_axi_data_BREADY : OUT STD_LOGIC;
        m_axi_data_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_data_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_data_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        sext_ln39 : IN STD_LOGIC_VECTOR (60 downto 0);
        reg_file_0_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_0_1_ce0 : OUT STD_LOGIC;
        reg_file_0_1_we0 : OUT STD_LOGIC;
        reg_file_0_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_0_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_0_1_ce1 : OUT STD_LOGIC;
        reg_file_0_1_we1 : OUT STD_LOGIC;
        reg_file_0_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_0_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_0_0_ce0 : OUT STD_LOGIC;
        reg_file_0_0_we0 : OUT STD_LOGIC;
        reg_file_0_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_0_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_0_0_ce1 : OUT STD_LOGIC;
        reg_file_0_0_we1 : OUT STD_LOGIC;
        reg_file_0_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_7_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_7_1_ce0 : OUT STD_LOGIC;
        reg_file_7_1_we0 : OUT STD_LOGIC;
        reg_file_7_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_7_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_7_1_ce1 : OUT STD_LOGIC;
        reg_file_7_1_we1 : OUT STD_LOGIC;
        reg_file_7_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_7_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_7_0_ce0 : OUT STD_LOGIC;
        reg_file_7_0_we0 : OUT STD_LOGIC;
        reg_file_7_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_7_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_7_0_ce1 : OUT STD_LOGIC;
        reg_file_7_0_we1 : OUT STD_LOGIC;
        reg_file_7_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_6_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_6_1_ce0 : OUT STD_LOGIC;
        reg_file_6_1_we0 : OUT STD_LOGIC;
        reg_file_6_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_6_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_6_1_ce1 : OUT STD_LOGIC;
        reg_file_6_1_we1 : OUT STD_LOGIC;
        reg_file_6_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_6_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_6_0_ce0 : OUT STD_LOGIC;
        reg_file_6_0_we0 : OUT STD_LOGIC;
        reg_file_6_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_6_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_6_0_ce1 : OUT STD_LOGIC;
        reg_file_6_0_we1 : OUT STD_LOGIC;
        reg_file_6_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_5_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_5_1_ce0 : OUT STD_LOGIC;
        reg_file_5_1_we0 : OUT STD_LOGIC;
        reg_file_5_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_5_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_5_1_ce1 : OUT STD_LOGIC;
        reg_file_5_1_we1 : OUT STD_LOGIC;
        reg_file_5_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_5_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_5_0_ce0 : OUT STD_LOGIC;
        reg_file_5_0_we0 : OUT STD_LOGIC;
        reg_file_5_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_5_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_5_0_ce1 : OUT STD_LOGIC;
        reg_file_5_0_we1 : OUT STD_LOGIC;
        reg_file_5_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_1_ce0 : OUT STD_LOGIC;
        reg_file_4_1_we0 : OUT STD_LOGIC;
        reg_file_4_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_1_ce1 : OUT STD_LOGIC;
        reg_file_4_1_we1 : OUT STD_LOGIC;
        reg_file_4_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_0_ce0 : OUT STD_LOGIC;
        reg_file_4_0_we0 : OUT STD_LOGIC;
        reg_file_4_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_4_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_4_0_ce1 : OUT STD_LOGIC;
        reg_file_4_0_we1 : OUT STD_LOGIC;
        reg_file_4_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_3_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_3_1_ce0 : OUT STD_LOGIC;
        reg_file_3_1_we0 : OUT STD_LOGIC;
        reg_file_3_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_3_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_3_1_ce1 : OUT STD_LOGIC;
        reg_file_3_1_we1 : OUT STD_LOGIC;
        reg_file_3_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_3_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_3_0_ce0 : OUT STD_LOGIC;
        reg_file_3_0_we0 : OUT STD_LOGIC;
        reg_file_3_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_3_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_3_0_ce1 : OUT STD_LOGIC;
        reg_file_3_0_we1 : OUT STD_LOGIC;
        reg_file_3_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_2_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_1_ce0 : OUT STD_LOGIC;
        reg_file_2_1_we0 : OUT STD_LOGIC;
        reg_file_2_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_2_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_1_ce1 : OUT STD_LOGIC;
        reg_file_2_1_we1 : OUT STD_LOGIC;
        reg_file_2_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_2_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_0_ce0 : OUT STD_LOGIC;
        reg_file_2_0_we0 : OUT STD_LOGIC;
        reg_file_2_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_2_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_2_0_ce1 : OUT STD_LOGIC;
        reg_file_2_0_we1 : OUT STD_LOGIC;
        reg_file_2_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_1_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_1_1_ce0 : OUT STD_LOGIC;
        reg_file_1_1_we0 : OUT STD_LOGIC;
        reg_file_1_1_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_1_1_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_1_1_ce1 : OUT STD_LOGIC;
        reg_file_1_1_we1 : OUT STD_LOGIC;
        reg_file_1_1_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_1_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_1_0_ce0 : OUT STD_LOGIC;
        reg_file_1_0_we0 : OUT STD_LOGIC;
        reg_file_1_0_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        reg_file_1_0_address1 : OUT STD_LOGIC_VECTOR (10 downto 0);
        reg_file_1_0_ce1 : OUT STD_LOGIC;
        reg_file_1_0_we1 : OUT STD_LOGIC;
        reg_file_1_0_d1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87 : component corr_accel_recv_data_burst_Pipeline_VITIS_LOOP_39_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start,
        ap_done => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done,
        ap_idle => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_idle,
        ap_ready => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_ready,
        m_axi_data_AWVALID => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWVALID,
        m_axi_data_AWREADY => ap_const_logic_0,
        m_axi_data_AWADDR => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWADDR,
        m_axi_data_AWID => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWID,
        m_axi_data_AWLEN => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWLEN,
        m_axi_data_AWSIZE => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWSIZE,
        m_axi_data_AWBURST => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWBURST,
        m_axi_data_AWLOCK => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWLOCK,
        m_axi_data_AWCACHE => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWCACHE,
        m_axi_data_AWPROT => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWPROT,
        m_axi_data_AWQOS => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWQOS,
        m_axi_data_AWREGION => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWREGION,
        m_axi_data_AWUSER => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_AWUSER,
        m_axi_data_WVALID => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WVALID,
        m_axi_data_WREADY => ap_const_logic_0,
        m_axi_data_WDATA => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WDATA,
        m_axi_data_WSTRB => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WSTRB,
        m_axi_data_WLAST => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WLAST,
        m_axi_data_WID => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WID,
        m_axi_data_WUSER => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_WUSER,
        m_axi_data_ARVALID => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARVALID,
        m_axi_data_ARREADY => m_axi_data_ARREADY,
        m_axi_data_ARADDR => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARADDR,
        m_axi_data_ARID => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARID,
        m_axi_data_ARLEN => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARLEN,
        m_axi_data_ARSIZE => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARSIZE,
        m_axi_data_ARBURST => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARBURST,
        m_axi_data_ARLOCK => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARLOCK,
        m_axi_data_ARCACHE => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARCACHE,
        m_axi_data_ARPROT => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARPROT,
        m_axi_data_ARQOS => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARQOS,
        m_axi_data_ARREGION => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARREGION,
        m_axi_data_ARUSER => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARUSER,
        m_axi_data_RVALID => m_axi_data_RVALID,
        m_axi_data_RREADY => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_RREADY,
        m_axi_data_RDATA => m_axi_data_RDATA,
        m_axi_data_RLAST => m_axi_data_RLAST,
        m_axi_data_RID => m_axi_data_RID,
        m_axi_data_RFIFONUM => m_axi_data_RFIFONUM,
        m_axi_data_RUSER => m_axi_data_RUSER,
        m_axi_data_RRESP => m_axi_data_RRESP,
        m_axi_data_BVALID => ap_const_logic_0,
        m_axi_data_BREADY => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_BREADY,
        m_axi_data_BRESP => ap_const_lv2_0,
        m_axi_data_BID => ap_const_lv1_0,
        m_axi_data_BUSER => ap_const_lv1_0,
        sext_ln39 => trunc_ln_reg_147,
        reg_file_0_1_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_address0,
        reg_file_0_1_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_ce0,
        reg_file_0_1_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_we0,
        reg_file_0_1_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_d0,
        reg_file_0_1_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_address1,
        reg_file_0_1_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_ce1,
        reg_file_0_1_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_we1,
        reg_file_0_1_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_d1,
        reg_file_0_0_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_address0,
        reg_file_0_0_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_ce0,
        reg_file_0_0_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_we0,
        reg_file_0_0_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_d0,
        reg_file_0_0_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_address1,
        reg_file_0_0_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_ce1,
        reg_file_0_0_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_we1,
        reg_file_0_0_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_d1,
        reg_file_7_1_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_address0,
        reg_file_7_1_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_ce0,
        reg_file_7_1_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_we0,
        reg_file_7_1_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_d0,
        reg_file_7_1_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_address1,
        reg_file_7_1_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_ce1,
        reg_file_7_1_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_we1,
        reg_file_7_1_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_d1,
        reg_file_7_0_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_address0,
        reg_file_7_0_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_ce0,
        reg_file_7_0_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_we0,
        reg_file_7_0_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_d0,
        reg_file_7_0_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_address1,
        reg_file_7_0_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_ce1,
        reg_file_7_0_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_we1,
        reg_file_7_0_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_d1,
        reg_file_6_1_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_address0,
        reg_file_6_1_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_ce0,
        reg_file_6_1_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_we0,
        reg_file_6_1_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_d0,
        reg_file_6_1_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_address1,
        reg_file_6_1_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_ce1,
        reg_file_6_1_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_we1,
        reg_file_6_1_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_d1,
        reg_file_6_0_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_address0,
        reg_file_6_0_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_ce0,
        reg_file_6_0_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_we0,
        reg_file_6_0_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_d0,
        reg_file_6_0_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_address1,
        reg_file_6_0_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_ce1,
        reg_file_6_0_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_we1,
        reg_file_6_0_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_d1,
        reg_file_5_1_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_address0,
        reg_file_5_1_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_ce0,
        reg_file_5_1_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_we0,
        reg_file_5_1_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_d0,
        reg_file_5_1_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_address1,
        reg_file_5_1_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_ce1,
        reg_file_5_1_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_we1,
        reg_file_5_1_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_d1,
        reg_file_5_0_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_address0,
        reg_file_5_0_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_ce0,
        reg_file_5_0_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_we0,
        reg_file_5_0_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_d0,
        reg_file_5_0_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_address1,
        reg_file_5_0_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_ce1,
        reg_file_5_0_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_we1,
        reg_file_5_0_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_d1,
        reg_file_4_1_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_address0,
        reg_file_4_1_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_ce0,
        reg_file_4_1_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_we0,
        reg_file_4_1_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_d0,
        reg_file_4_1_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_address1,
        reg_file_4_1_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_ce1,
        reg_file_4_1_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_we1,
        reg_file_4_1_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_d1,
        reg_file_4_0_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_address0,
        reg_file_4_0_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_ce0,
        reg_file_4_0_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_we0,
        reg_file_4_0_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_d0,
        reg_file_4_0_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_address1,
        reg_file_4_0_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_ce1,
        reg_file_4_0_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_we1,
        reg_file_4_0_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_d1,
        reg_file_3_1_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_address0,
        reg_file_3_1_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_ce0,
        reg_file_3_1_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_we0,
        reg_file_3_1_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_d0,
        reg_file_3_1_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_address1,
        reg_file_3_1_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_ce1,
        reg_file_3_1_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_we1,
        reg_file_3_1_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_d1,
        reg_file_3_0_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_address0,
        reg_file_3_0_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_ce0,
        reg_file_3_0_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_we0,
        reg_file_3_0_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_d0,
        reg_file_3_0_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_address1,
        reg_file_3_0_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_ce1,
        reg_file_3_0_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_we1,
        reg_file_3_0_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_d1,
        reg_file_2_1_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_address0,
        reg_file_2_1_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_ce0,
        reg_file_2_1_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_we0,
        reg_file_2_1_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_d0,
        reg_file_2_1_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_address1,
        reg_file_2_1_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_ce1,
        reg_file_2_1_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_we1,
        reg_file_2_1_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_d1,
        reg_file_2_0_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_address0,
        reg_file_2_0_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_ce0,
        reg_file_2_0_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_we0,
        reg_file_2_0_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_d0,
        reg_file_2_0_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_address1,
        reg_file_2_0_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_ce1,
        reg_file_2_0_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_we1,
        reg_file_2_0_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_d1,
        reg_file_1_1_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_address0,
        reg_file_1_1_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_ce0,
        reg_file_1_1_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_we0,
        reg_file_1_1_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_d0,
        reg_file_1_1_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_address1,
        reg_file_1_1_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_ce1,
        reg_file_1_1_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_we1,
        reg_file_1_1_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_d1,
        reg_file_1_0_address0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_address0,
        reg_file_1_0_ce0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_ce0,
        reg_file_1_0_we0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_we0,
        reg_file_1_0_d0 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_d0,
        reg_file_1_0_address1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_address1,
        reg_file_1_0_ce1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_ce1,
        reg_file_1_0_we1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_we1,
        reg_file_1_0_d1 => grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_d1);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_ready = ap_const_logic_1)) then 
                    grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                trunc_ln_reg_147 <= data_in(63 downto 3);
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, m_axi_data_ARREADY, grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done, ap_CS_fsm_state9)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((m_axi_data_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start, m_axi_data_ARREADY)
    begin
        if (((m_axi_data_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;
    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done)
    begin
        if ((grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done, ap_CS_fsm_state9)
    begin
        if ((((grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9)) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done, ap_CS_fsm_state9)
    begin
        if (((grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    data_blk_n_AR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_data_ARREADY)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
            data_blk_n_AR <= m_axi_data_ARREADY;
        else 
            data_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;

    grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_ap_start_reg;

    m_axi_data_ARADDR_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_data_ARREADY, grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARADDR, ap_CS_fsm_state8, ap_CS_fsm_state9, sext_ln39_fu_136_p1)
    begin
        if ((not(((m_axi_data_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_data_ARADDR <= sext_ln39_fu_136_p1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARADDR <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARADDR;
        else 
            m_axi_data_ARADDR <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_data_ARBURST_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARBURST, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARBURST <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARBURST;
        else 
            m_axi_data_ARBURST <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_data_ARCACHE_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARCACHE, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARCACHE <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARCACHE;
        else 
            m_axi_data_ARCACHE <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_data_ARID_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARID, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARID <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARID;
        else 
            m_axi_data_ARID <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_data_ARLEN_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_data_ARREADY, grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARLEN, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((not(((m_axi_data_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_data_ARLEN <= ap_const_lv32_2000;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARLEN <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARLEN;
        else 
            m_axi_data_ARLEN <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    m_axi_data_ARLOCK_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARLOCK, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARLOCK <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARLOCK;
        else 
            m_axi_data_ARLOCK <= ap_const_lv2_0;
        end if; 
    end process;


    m_axi_data_ARPROT_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARPROT, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARPROT <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARPROT;
        else 
            m_axi_data_ARPROT <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_data_ARQOS_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARQOS, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARQOS <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARQOS;
        else 
            m_axi_data_ARQOS <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_data_ARREGION_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARREGION, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARREGION <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARREGION;
        else 
            m_axi_data_ARREGION <= ap_const_lv4_0;
        end if; 
    end process;


    m_axi_data_ARSIZE_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARSIZE, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARSIZE <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARSIZE;
        else 
            m_axi_data_ARSIZE <= ap_const_lv3_0;
        end if; 
    end process;


    m_axi_data_ARUSER_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARUSER, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARUSER <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARUSER;
        else 
            m_axi_data_ARUSER <= ap_const_lv1_0;
        end if; 
    end process;


    m_axi_data_ARVALID_assign_proc : process(ap_start, ap_CS_fsm_state1, m_axi_data_ARREADY, grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARVALID, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if ((not(((m_axi_data_ARREADY = ap_const_logic_0) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            m_axi_data_ARVALID <= ap_const_logic_1;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_ARVALID <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_ARVALID;
        else 
            m_axi_data_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_data_AWADDR <= ap_const_lv64_0;
    m_axi_data_AWBURST <= ap_const_lv2_0;
    m_axi_data_AWCACHE <= ap_const_lv4_0;
    m_axi_data_AWID <= ap_const_lv1_0;
    m_axi_data_AWLEN <= ap_const_lv32_0;
    m_axi_data_AWLOCK <= ap_const_lv2_0;
    m_axi_data_AWPROT <= ap_const_lv3_0;
    m_axi_data_AWQOS <= ap_const_lv4_0;
    m_axi_data_AWREGION <= ap_const_lv4_0;
    m_axi_data_AWSIZE <= ap_const_lv3_0;
    m_axi_data_AWUSER <= ap_const_lv1_0;
    m_axi_data_AWVALID <= ap_const_logic_0;
    m_axi_data_BREADY <= ap_const_logic_0;

    m_axi_data_RREADY_assign_proc : process(grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_RREADY, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state9) or (ap_const_logic_1 = ap_CS_fsm_state8))) then 
            m_axi_data_RREADY <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_m_axi_data_RREADY;
        else 
            m_axi_data_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_data_WDATA <= ap_const_lv64_0;
    m_axi_data_WID <= ap_const_lv1_0;
    m_axi_data_WLAST <= ap_const_logic_0;
    m_axi_data_WSTRB <= ap_const_lv8_0;
    m_axi_data_WUSER <= ap_const_lv1_0;
    m_axi_data_WVALID <= ap_const_logic_0;
    reg_file_0_0_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_address0;
    reg_file_0_0_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_address1;
    reg_file_0_0_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_ce0;
    reg_file_0_0_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_ce1;
    reg_file_0_0_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_d0;
    reg_file_0_0_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_d1;
    reg_file_0_0_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_we0;
    reg_file_0_0_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_0_we1;
    reg_file_0_1_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_address0;
    reg_file_0_1_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_address1;
    reg_file_0_1_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_ce0;
    reg_file_0_1_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_ce1;
    reg_file_0_1_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_d0;
    reg_file_0_1_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_d1;
    reg_file_0_1_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_we0;
    reg_file_0_1_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_0_1_we1;
    reg_file_1_0_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_address0;
    reg_file_1_0_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_address1;
    reg_file_1_0_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_ce0;
    reg_file_1_0_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_ce1;
    reg_file_1_0_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_d0;
    reg_file_1_0_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_d1;
    reg_file_1_0_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_we0;
    reg_file_1_0_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_0_we1;
    reg_file_1_1_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_address0;
    reg_file_1_1_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_address1;
    reg_file_1_1_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_ce0;
    reg_file_1_1_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_ce1;
    reg_file_1_1_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_d0;
    reg_file_1_1_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_d1;
    reg_file_1_1_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_we0;
    reg_file_1_1_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_1_1_we1;
    reg_file_2_0_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_address0;
    reg_file_2_0_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_address1;
    reg_file_2_0_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_ce0;
    reg_file_2_0_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_ce1;
    reg_file_2_0_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_d0;
    reg_file_2_0_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_d1;
    reg_file_2_0_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_we0;
    reg_file_2_0_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_0_we1;
    reg_file_2_1_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_address0;
    reg_file_2_1_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_address1;
    reg_file_2_1_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_ce0;
    reg_file_2_1_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_ce1;
    reg_file_2_1_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_d0;
    reg_file_2_1_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_d1;
    reg_file_2_1_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_we0;
    reg_file_2_1_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_2_1_we1;
    reg_file_3_0_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_address0;
    reg_file_3_0_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_address1;
    reg_file_3_0_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_ce0;
    reg_file_3_0_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_ce1;
    reg_file_3_0_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_d0;
    reg_file_3_0_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_d1;
    reg_file_3_0_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_we0;
    reg_file_3_0_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_0_we1;
    reg_file_3_1_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_address0;
    reg_file_3_1_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_address1;
    reg_file_3_1_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_ce0;
    reg_file_3_1_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_ce1;
    reg_file_3_1_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_d0;
    reg_file_3_1_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_d1;
    reg_file_3_1_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_we0;
    reg_file_3_1_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_3_1_we1;
    reg_file_4_0_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_address0;
    reg_file_4_0_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_address1;
    reg_file_4_0_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_ce0;
    reg_file_4_0_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_ce1;
    reg_file_4_0_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_d0;
    reg_file_4_0_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_d1;
    reg_file_4_0_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_we0;
    reg_file_4_0_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_0_we1;
    reg_file_4_1_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_address0;
    reg_file_4_1_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_address1;
    reg_file_4_1_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_ce0;
    reg_file_4_1_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_ce1;
    reg_file_4_1_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_d0;
    reg_file_4_1_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_d1;
    reg_file_4_1_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_we0;
    reg_file_4_1_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_4_1_we1;
    reg_file_5_0_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_address0;
    reg_file_5_0_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_address1;
    reg_file_5_0_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_ce0;
    reg_file_5_0_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_ce1;
    reg_file_5_0_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_d0;
    reg_file_5_0_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_d1;
    reg_file_5_0_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_we0;
    reg_file_5_0_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_0_we1;
    reg_file_5_1_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_address0;
    reg_file_5_1_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_address1;
    reg_file_5_1_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_ce0;
    reg_file_5_1_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_ce1;
    reg_file_5_1_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_d0;
    reg_file_5_1_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_d1;
    reg_file_5_1_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_we0;
    reg_file_5_1_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_5_1_we1;
    reg_file_6_0_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_address0;
    reg_file_6_0_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_address1;
    reg_file_6_0_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_ce0;
    reg_file_6_0_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_ce1;
    reg_file_6_0_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_d0;
    reg_file_6_0_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_d1;
    reg_file_6_0_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_we0;
    reg_file_6_0_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_0_we1;
    reg_file_6_1_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_address0;
    reg_file_6_1_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_address1;
    reg_file_6_1_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_ce0;
    reg_file_6_1_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_ce1;
    reg_file_6_1_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_d0;
    reg_file_6_1_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_d1;
    reg_file_6_1_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_we0;
    reg_file_6_1_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_6_1_we1;
    reg_file_7_0_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_address0;
    reg_file_7_0_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_address1;
    reg_file_7_0_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_ce0;
    reg_file_7_0_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_ce1;
    reg_file_7_0_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_d0;
    reg_file_7_0_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_d1;
    reg_file_7_0_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_we0;
    reg_file_7_0_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_0_we1;
    reg_file_7_1_address0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_address0;
    reg_file_7_1_address1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_address1;
    reg_file_7_1_ce0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_ce0;
    reg_file_7_1_ce1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_ce1;
    reg_file_7_1_d0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_d0;
    reg_file_7_1_d1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_d1;
    reg_file_7_1_we0 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_we0;
    reg_file_7_1_we1 <= grp_recv_data_burst_Pipeline_VITIS_LOOP_39_1_fu_87_reg_file_7_1_we1;
        sext_ln39_fu_136_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_126_p4),64));

    trunc_ln_fu_126_p4 <= data_in(63 downto 3);
end behav;
